/* Tab.c generated by valac 0.20.1.4-f5a54, the Vala compiler
 * generated from Tab.vala, do not modify */

/**/
/*  Copyright (C) 2011-2012 Robert Dyer, Michal Hruby, Rico Tzschichholz*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include <cairo.h>


#define SHELF_ITEMS_TYPE_TAB (shelf_items_tab_get_type ())
#define SHELF_ITEMS_TAB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_ITEMS_TYPE_TAB, ShelfItemsTab))
#define SHELF_ITEMS_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_ITEMS_TYPE_TAB, ShelfItemsTabClass))
#define SHELF_ITEMS_IS_TAB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_ITEMS_TYPE_TAB))
#define SHELF_ITEMS_IS_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_ITEMS_TYPE_TAB))
#define SHELF_ITEMS_TAB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_ITEMS_TYPE_TAB, ShelfItemsTabClass))

typedef struct _ShelfItemsTab ShelfItemsTab;
typedef struct _ShelfItemsTabClass ShelfItemsTabClass;
typedef struct _ShelfItemsTabPrivate ShelfItemsTabPrivate;

#define SHELF_DRAWING_TYPE_TAB_RENDERER (shelf_drawing_tab_renderer_get_type ())
#define SHELF_DRAWING_TAB_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_DRAWING_TYPE_TAB_RENDERER, ShelfDrawingTabRenderer))
#define SHELF_DRAWING_TAB_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_DRAWING_TYPE_TAB_RENDERER, ShelfDrawingTabRendererClass))
#define SHELF_DRAWING_IS_TAB_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_DRAWING_TYPE_TAB_RENDERER))
#define SHELF_DRAWING_IS_TAB_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_DRAWING_TYPE_TAB_RENDERER))
#define SHELF_DRAWING_TAB_RENDERER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_DRAWING_TYPE_TAB_RENDERER, ShelfDrawingTabRendererClass))

typedef struct _ShelfDrawingTabRenderer ShelfDrawingTabRenderer;
typedef struct _ShelfDrawingTabRendererClass ShelfDrawingTabRendererClass;

#define SHELF_ITEMS_TYPE_TAB_MANAGER (shelf_items_tab_manager_get_type ())
#define SHELF_ITEMS_TAB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManager))
#define SHELF_ITEMS_TAB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManagerClass))
#define SHELF_ITEMS_IS_TAB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_ITEMS_TYPE_TAB_MANAGER))
#define SHELF_ITEMS_IS_TAB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_ITEMS_TYPE_TAB_MANAGER))
#define SHELF_ITEMS_TAB_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManagerClass))

typedef struct _ShelfItemsTabManager ShelfItemsTabManager;
typedef struct _ShelfItemsTabManagerClass ShelfItemsTabManagerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _ShelfItemsTab {
	GObject parent_instance;
	ShelfItemsTabPrivate * priv;
};

struct _ShelfItemsTabClass {
	GObjectClass parent_class;
};

struct _ShelfItemsTabPrivate {
	ShelfDrawingTabRenderer* tab_renderer;
	ShelfItemsTabManager* _tab_manager;
};


static gpointer shelf_items_tab_parent_class = NULL;

GType shelf_items_tab_get_type (void) G_GNUC_CONST;
GType shelf_drawing_tab_renderer_get_type (void) G_GNUC_CONST;
GType shelf_items_tab_manager_get_type (void) G_GNUC_CONST;
#define SHELF_ITEMS_TAB_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SHELF_ITEMS_TYPE_TAB, ShelfItemsTabPrivate))
enum  {
	SHELF_ITEMS_TAB_DUMMY_PROPERTY,
	SHELF_ITEMS_TAB_TAB_MANAGER
};
ShelfItemsTab* shelf_items_tab_new (ShelfItemsTabManager* manager);
ShelfItemsTab* shelf_items_tab_construct (GType object_type, ShelfItemsTabManager* manager);
void shelf_items_tab_draw (ShelfItemsTab* self, cairo_t* cr, gint position);
void shelf_drawing_tab_renderer_draw (ShelfDrawingTabRenderer* self, cairo_t* cr, gint position);
static ShelfItemsTabManager* shelf_items_tab_get_tab_manager (ShelfItemsTab* self);
static void shelf_items_tab_set_tab_manager (ShelfItemsTab* self, ShelfItemsTabManager* value);
static GObject * shelf_items_tab_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
ShelfDrawingTabRenderer* shelf_drawing_tab_renderer_new (void);
ShelfDrawingTabRenderer* shelf_drawing_tab_renderer_construct (GType object_type);
static void shelf_items_tab_finalize (GObject* obj);
static void _vala_shelf_items_tab_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_shelf_items_tab_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


/**
 * Creates a new item manager.
 */
ShelfItemsTab* shelf_items_tab_construct (GType object_type, ShelfItemsTabManager* manager) {
	ShelfItemsTab * self = NULL;
	ShelfItemsTabManager* _tmp0_;
#line 38 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	g_return_val_if_fail (manager != NULL, NULL);
#line 40 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	_tmp0_ = manager;
#line 40 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	self = (ShelfItemsTab*) g_object_new (object_type, "tab-manager", _tmp0_, NULL);
#line 38 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	return self;
#line 112 "Tab.c"
}


ShelfItemsTab* shelf_items_tab_new (ShelfItemsTabManager* manager) {
#line 38 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	return shelf_items_tab_construct (SHELF_ITEMS_TYPE_TAB, manager);
#line 119 "Tab.c"
}


/**
 * Draws a tab.
 */
void shelf_items_tab_draw (ShelfItemsTab* self, cairo_t* cr, gint position) {
	ShelfDrawingTabRenderer* _tmp0_;
	cairo_t* _tmp1_;
	gint _tmp2_;
#line 55 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	g_return_if_fail (self != NULL);
#line 55 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	g_return_if_fail (cr != NULL);
#line 57 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	_tmp0_ = self->priv->tab_renderer;
#line 57 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	_tmp1_ = cr;
#line 57 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	_tmp2_ = position;
#line 57 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	shelf_drawing_tab_renderer_draw (_tmp0_, _tmp1_, _tmp2_);
#line 142 "Tab.c"
}


static ShelfItemsTabManager* shelf_items_tab_get_tab_manager (ShelfItemsTab* self) {
	ShelfItemsTabManager* result;
	ShelfItemsTabManager* _tmp0_;
#line 33 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 33 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	_tmp0_ = self->priv->_tab_manager;
#line 33 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	result = _tmp0_;
#line 33 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	return result;
#line 157 "Tab.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 33 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	return self ? g_object_ref (self) : NULL;
#line 164 "Tab.c"
}


static void shelf_items_tab_set_tab_manager (ShelfItemsTab* self, ShelfItemsTabManager* value) {
	ShelfItemsTabManager* _tmp0_;
	ShelfItemsTabManager* _tmp1_;
#line 33 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	g_return_if_fail (self != NULL);
#line 33 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	_tmp0_ = value;
#line 33 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 33 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	_g_object_unref0 (self->priv->_tab_manager);
#line 33 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	self->priv->_tab_manager = _tmp1_;
#line 33 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	g_object_notify ((GObject *) self, "tab-manager");
#line 183 "Tab.c"
}


static GObject * shelf_items_tab_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	ShelfItemsTab * self;
	ShelfDrawingTabRenderer* _tmp0_;
#line 43 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	parent_class = G_OBJECT_CLASS (shelf_items_tab_parent_class);
#line 43 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 43 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHELF_ITEMS_TYPE_TAB, ShelfItemsTab);
#line 45 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	_tmp0_ = shelf_drawing_tab_renderer_new ();
#line 45 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	_g_object_unref0 (self->priv->tab_renderer);
#line 45 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	self->priv->tab_renderer = _tmp0_;
#line 43 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	return obj;
#line 206 "Tab.c"
}


static void shelf_items_tab_class_init (ShelfItemsTabClass * klass) {
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	shelf_items_tab_parent_class = g_type_class_peek_parent (klass);
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	g_type_class_add_private (klass, sizeof (ShelfItemsTabPrivate));
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_shelf_items_tab_get_property;
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_shelf_items_tab_set_property;
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	G_OBJECT_CLASS (klass)->constructor = shelf_items_tab_constructor;
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	G_OBJECT_CLASS (klass)->finalize = shelf_items_tab_finalize;
#line 223 "Tab.c"
	/**
	 * The tab manager.
	 */
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SHELF_ITEMS_TAB_TAB_MANAGER, g_param_spec_object ("tab-manager", "tab-manager", "tab-manager", SHELF_ITEMS_TYPE_TAB_MANAGER, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 229 "Tab.c"
}


static void shelf_items_tab_instance_init (ShelfItemsTab * self) {
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	self->priv = SHELF_ITEMS_TAB_GET_PRIVATE (self);
#line 236 "Tab.c"
}


static void shelf_items_tab_finalize (GObject* obj) {
	ShelfItemsTab * self;
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHELF_ITEMS_TYPE_TAB, ShelfItemsTab);
#line 28 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	_g_object_unref0 (self->priv->tab_renderer);
#line 33 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	_g_object_unref0 (self->priv->_tab_manager);
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	G_OBJECT_CLASS (shelf_items_tab_parent_class)->finalize (obj);
#line 250 "Tab.c"
}


/**
 * The main manager for dock items.
 */
GType shelf_items_tab_get_type (void) {
	static volatile gsize shelf_items_tab_type_id__volatile = 0;
	if (g_once_init_enter (&shelf_items_tab_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ShelfItemsTabClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) shelf_items_tab_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ShelfItemsTab), 0, (GInstanceInitFunc) shelf_items_tab_instance_init, NULL };
		GType shelf_items_tab_type_id;
		shelf_items_tab_type_id = g_type_register_static (G_TYPE_OBJECT, "ShelfItemsTab", &g_define_type_info, 0);
		g_once_init_leave (&shelf_items_tab_type_id__volatile, shelf_items_tab_type_id);
	}
	return shelf_items_tab_type_id__volatile;
}


static void _vala_shelf_items_tab_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	ShelfItemsTab * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SHELF_ITEMS_TYPE_TAB, ShelfItemsTab);
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	switch (property_id) {
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
		case SHELF_ITEMS_TAB_TAB_MANAGER:
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
		g_value_set_object (value, shelf_items_tab_get_tab_manager (self));
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
		break;
#line 280 "Tab.c"
		default:
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
		break;
#line 286 "Tab.c"
	}
}


static void _vala_shelf_items_tab_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	ShelfItemsTab * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SHELF_ITEMS_TYPE_TAB, ShelfItemsTab);
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
	switch (property_id) {
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
		case SHELF_ITEMS_TAB_TAB_MANAGER:
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
		shelf_items_tab_set_tab_manager (self, g_value_get_object (value));
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
		break;
#line 302 "Tab.c"
		default:
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 26 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Items/Tab.vala"
		break;
#line 308 "Tab.c"
	}
}



