/* Tab.c generated by valac 0.20.1.4-f5a54, the Vala compiler
 * generated from Tab.vala, do not modify */

/**/
/*  Copyright (C) 2011-2012 Robert Dyer, Michal Hruby, Rico Tzschichholz*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include <cairo.h>
#include <gdk/gdk.h>
#include <stdio.h>
#include <float.h>
#include <math.h>


#define SHELF_ITEMS_TYPE_TAB (shelf_items_tab_get_type ())
#define SHELF_ITEMS_TAB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_ITEMS_TYPE_TAB, ShelfItemsTab))
#define SHELF_ITEMS_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_ITEMS_TYPE_TAB, ShelfItemsTabClass))
#define SHELF_ITEMS_IS_TAB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_ITEMS_TYPE_TAB))
#define SHELF_ITEMS_IS_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_ITEMS_TYPE_TAB))
#define SHELF_ITEMS_TAB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_ITEMS_TYPE_TAB, ShelfItemsTabClass))

typedef struct _ShelfItemsTab ShelfItemsTab;
typedef struct _ShelfItemsTabClass ShelfItemsTabClass;
typedef struct _ShelfItemsTabPrivate ShelfItemsTabPrivate;

#define SHELF_DRAWING_TYPE_TAB_RENDERER (shelf_drawing_tab_renderer_get_type ())
#define SHELF_DRAWING_TAB_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_DRAWING_TYPE_TAB_RENDERER, ShelfDrawingTabRenderer))
#define SHELF_DRAWING_TAB_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_DRAWING_TYPE_TAB_RENDERER, ShelfDrawingTabRendererClass))
#define SHELF_DRAWING_IS_TAB_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_DRAWING_TYPE_TAB_RENDERER))
#define SHELF_DRAWING_IS_TAB_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_DRAWING_TYPE_TAB_RENDERER))
#define SHELF_DRAWING_TAB_RENDERER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_DRAWING_TYPE_TAB_RENDERER, ShelfDrawingTabRendererClass))

typedef struct _ShelfDrawingTabRenderer ShelfDrawingTabRenderer;
typedef struct _ShelfDrawingTabRendererClass ShelfDrawingTabRendererClass;

#define SHELF_ITEMS_TYPE_TAB_MANAGER (shelf_items_tab_manager_get_type ())
#define SHELF_ITEMS_TAB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManager))
#define SHELF_ITEMS_TAB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManagerClass))
#define SHELF_ITEMS_IS_TAB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_ITEMS_TYPE_TAB_MANAGER))
#define SHELF_ITEMS_IS_TAB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_ITEMS_TYPE_TAB_MANAGER))
#define SHELF_ITEMS_TAB_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManagerClass))

typedef struct _ShelfItemsTabManager ShelfItemsTabManager;
typedef struct _ShelfItemsTabManagerClass ShelfItemsTabManagerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _ShelfItemsTabManagerPrivate ShelfItemsTabManagerPrivate;

struct _ShelfItemsTab {
	GObject parent_instance;
	ShelfItemsTabPrivate * priv;
	ShelfDrawingTabRenderer* tab_renderer;
	gboolean hovered;
};

struct _ShelfItemsTabClass {
	GObjectClass parent_class;
};

struct _ShelfItemsTabPrivate {
	ShelfItemsTabManager* _tab_manager;
};

struct _ShelfItemsTabManager {
	GObject parent_instance;
	ShelfItemsTabManagerPrivate * priv;
	gint tab_icon_size;
	gint tab_margin;
};

struct _ShelfItemsTabManagerClass {
	GObjectClass parent_class;
};


static gpointer shelf_items_tab_parent_class = NULL;

GType shelf_items_tab_get_type (void) G_GNUC_CONST;
GType shelf_drawing_tab_renderer_get_type (void) G_GNUC_CONST;
GType shelf_items_tab_manager_get_type (void) G_GNUC_CONST;
#define SHELF_ITEMS_TAB_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SHELF_ITEMS_TYPE_TAB, ShelfItemsTabPrivate))
enum  {
	SHELF_ITEMS_TAB_DUMMY_PROPERTY,
	SHELF_ITEMS_TAB_TAB_MANAGER
};
ShelfItemsTab* shelf_items_tab_new (ShelfItemsTabManager* manager);
ShelfItemsTab* shelf_items_tab_construct (GType object_type, ShelfItemsTabManager* manager);
void shelf_items_tab_draw (ShelfItemsTab* self, cairo_t* cr, gint position);
void shelf_drawing_tab_renderer_draw (ShelfDrawingTabRenderer* self, cairo_t* cr, gint position);
gboolean shelf_items_tab_is_mouse_inside_tab (ShelfItemsTab* self, GdkEventMotion* event);
ShelfItemsTabManager* shelf_items_tab_get_tab_manager (ShelfItemsTab* self);
gint shelf_items_tab_manager_get_tab_position (ShelfItemsTabManager* self, ShelfItemsTab* t);
static void shelf_items_tab_set_tab_manager (ShelfItemsTab* self, ShelfItemsTabManager* value);
static GObject * shelf_items_tab_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
ShelfDrawingTabRenderer* shelf_drawing_tab_renderer_new (ShelfItemsTab* the_tab);
ShelfDrawingTabRenderer* shelf_drawing_tab_renderer_construct (GType object_type, ShelfItemsTab* the_tab);
static void shelf_items_tab_finalize (GObject* obj);
static void _vala_shelf_items_tab_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_shelf_items_tab_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


/**
 * Creates a new item manager.
 */
ShelfItemsTab* shelf_items_tab_construct (GType object_type, ShelfItemsTabManager* manager) {
	ShelfItemsTab * self = NULL;
	ShelfItemsTabManager* _tmp0_;
#line 40 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	g_return_val_if_fail (manager != NULL, NULL);
#line 42 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp0_ = manager;
#line 42 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	self = (ShelfItemsTab*) g_object_new (object_type, "tab-manager", _tmp0_, NULL);
#line 40 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	return self;
#line 131 "Tab.c"
}


ShelfItemsTab* shelf_items_tab_new (ShelfItemsTabManager* manager) {
#line 40 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	return shelf_items_tab_construct (SHELF_ITEMS_TYPE_TAB, manager);
#line 138 "Tab.c"
}


/**
 * Draws a tab.
 */
void shelf_items_tab_draw (ShelfItemsTab* self, cairo_t* cr, gint position) {
	ShelfDrawingTabRenderer* _tmp0_;
	cairo_t* _tmp1_;
	gint _tmp2_;
#line 58 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	g_return_if_fail (self != NULL);
#line 58 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	g_return_if_fail (cr != NULL);
#line 60 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp0_ = self->tab_renderer;
#line 60 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp1_ = cr;
#line 60 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp2_ = position;
#line 60 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	shelf_drawing_tab_renderer_draw (_tmp0_, _tmp1_, _tmp2_);
#line 161 "Tab.c"
}


gboolean shelf_items_tab_is_mouse_inside_tab (ShelfItemsTab* self, GdkEventMotion* event) {
	gboolean result = FALSE;
	gint tab_x;
	ShelfItemsTabManager* _tmp0_;
	gint _tmp1_;
	ShelfItemsTabManager* _tmp2_;
	gint _tmp3_;
	ShelfItemsTabManager* _tmp4_;
	gint _tmp5_ = 0;
	gint tab_y;
	ShelfItemsTabManager* _tmp6_;
	gint _tmp7_;
	ShelfItemsTabManager* _tmp8_;
	gint _tmp9_;
	ShelfItemsTabManager* _tmp10_;
	gint _tmp11_ = 0;
	gint next_tab_y;
	FILE* _tmp12_;
	ShelfItemsTabManager* _tmp13_;
	gint _tmp14_ = 0;
	GdkEventMotion _tmp15_;
	gdouble _tmp16_;
	GdkEventMotion _tmp17_;
	gdouble _tmp18_;
	gint _tmp19_;
	gint _tmp20_;
	GdkEventMotion _tmp21_;
	gdouble _tmp22_;
#line 63 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 63 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 65 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	tab_x = 0;
#line 66 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp0_ = self->priv->_tab_manager;
#line 66 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp1_ = _tmp0_->tab_icon_size;
#line 66 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp2_ = self->priv->_tab_manager;
#line 66 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp3_ = _tmp2_->tab_margin;
#line 66 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp4_ = self->priv->_tab_manager;
#line 66 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp5_ = shelf_items_tab_manager_get_tab_position (_tmp4_, self);
#line 66 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	tab_y = (_tmp1_ + (_tmp3_ * 3)) * _tmp5_;
#line 67 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp6_ = self->priv->_tab_manager;
#line 67 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp7_ = _tmp6_->tab_icon_size;
#line 67 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp8_ = self->priv->_tab_manager;
#line 67 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp9_ = _tmp8_->tab_margin;
#line 67 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp10_ = self->priv->_tab_manager;
#line 67 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp11_ = shelf_items_tab_manager_get_tab_position (_tmp10_, self);
#line 67 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	next_tab_y = (_tmp7_ + (_tmp9_ * 3)) * (_tmp11_ + 1);
#line 69 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp12_ = stdout;
#line 69 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp13_ = self->priv->_tab_manager;
#line 69 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp14_ = shelf_items_tab_manager_get_tab_position (_tmp13_, self);
#line 69 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp15_ = *event;
#line 69 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp16_ = _tmp15_.x;
#line 69 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp17_ = *event;
#line 69 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp18_ = _tmp17_.y;
#line 69 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp19_ = tab_y;
#line 69 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp20_ = next_tab_y;
#line 69 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	fprintf (_tmp12_, "tab %d. mouse : %lf,%lf. tab_y=%d. next_tab_y=%d\n", _tmp14_, _tmp16_, _tmp18_, _tmp19_, _tmp20_);
#line 71 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp21_ = *event;
#line 71 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp22_ = _tmp21_.x;
#line 71 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	if (_tmp22_ < ((gdouble) 48)) {
#line 253 "Tab.c"
		gboolean _tmp23_ = FALSE;
		GdkEventMotion _tmp24_;
		gdouble _tmp25_;
		gint _tmp26_;
		gboolean _tmp30_;
#line 73 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
		_tmp24_ = *event;
#line 73 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
		_tmp25_ = _tmp24_.y;
#line 73 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
		_tmp26_ = next_tab_y;
#line 73 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
		if (_tmp25_ < ((gdouble) _tmp26_)) {
#line 267 "Tab.c"
			GdkEventMotion _tmp27_;
			gdouble _tmp28_;
			gint _tmp29_;
#line 73 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
			_tmp27_ = *event;
#line 73 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
			_tmp28_ = _tmp27_.y;
#line 73 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
			_tmp29_ = tab_y;
#line 73 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
			_tmp23_ = _tmp28_ > ((gdouble) _tmp29_);
#line 279 "Tab.c"
		} else {
#line 73 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
			_tmp23_ = FALSE;
#line 283 "Tab.c"
		}
#line 73 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
		_tmp30_ = _tmp23_;
#line 73 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
		if (_tmp30_) {
#line 75 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
			result = TRUE;
#line 75 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
			return result;
#line 293 "Tab.c"
		}
	}
#line 79 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	result = FALSE;
#line 79 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	return result;
#line 300 "Tab.c"
}


ShelfItemsTabManager* shelf_items_tab_get_tab_manager (ShelfItemsTab* self) {
	ShelfItemsTabManager* result;
	ShelfItemsTabManager* _tmp0_;
#line 35 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 35 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp0_ = self->priv->_tab_manager;
#line 35 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	result = _tmp0_;
#line 35 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	return result;
#line 315 "Tab.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 35 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	return self ? g_object_ref (self) : NULL;
#line 322 "Tab.c"
}


static void shelf_items_tab_set_tab_manager (ShelfItemsTab* self, ShelfItemsTabManager* value) {
	ShelfItemsTabManager* _tmp0_;
	ShelfItemsTabManager* _tmp1_;
#line 35 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	g_return_if_fail (self != NULL);
#line 35 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp0_ = value;
#line 35 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 35 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_g_object_unref0 (self->priv->_tab_manager);
#line 35 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	self->priv->_tab_manager = _tmp1_;
#line 35 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	g_object_notify ((GObject *) self, "tab-manager");
#line 341 "Tab.c"
}


static GObject * shelf_items_tab_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	ShelfItemsTab * self;
	ShelfDrawingTabRenderer* _tmp0_;
#line 45 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	parent_class = G_OBJECT_CLASS (shelf_items_tab_parent_class);
#line 45 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 45 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHELF_ITEMS_TYPE_TAB, ShelfItemsTab);
#line 47 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_tmp0_ = shelf_drawing_tab_renderer_new (self);
#line 47 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_g_object_unref0 (self->tab_renderer);
#line 47 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	self->tab_renderer = _tmp0_;
#line 48 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	self->hovered = FALSE;
#line 45 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	return obj;
#line 366 "Tab.c"
}


static void shelf_items_tab_class_init (ShelfItemsTabClass * klass) {
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	shelf_items_tab_parent_class = g_type_class_peek_parent (klass);
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	g_type_class_add_private (klass, sizeof (ShelfItemsTabPrivate));
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_shelf_items_tab_get_property;
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_shelf_items_tab_set_property;
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	G_OBJECT_CLASS (klass)->constructor = shelf_items_tab_constructor;
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	G_OBJECT_CLASS (klass)->finalize = shelf_items_tab_finalize;
#line 383 "Tab.c"
	/**
	 * The tab manager.
	 */
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SHELF_ITEMS_TAB_TAB_MANAGER, g_param_spec_object ("tab-manager", "tab-manager", "tab-manager", SHELF_ITEMS_TYPE_TAB_MANAGER, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 389 "Tab.c"
}


static void shelf_items_tab_instance_init (ShelfItemsTab * self) {
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	self->priv = SHELF_ITEMS_TAB_GET_PRIVATE (self);
#line 396 "Tab.c"
}


static void shelf_items_tab_finalize (GObject* obj) {
	ShelfItemsTab * self;
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHELF_ITEMS_TYPE_TAB, ShelfItemsTab);
#line 29 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_g_object_unref0 (self->tab_renderer);
#line 35 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	_g_object_unref0 (self->priv->_tab_manager);
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	G_OBJECT_CLASS (shelf_items_tab_parent_class)->finalize (obj);
#line 410 "Tab.c"
}


/**
 * The main manager for dock items.
 */
GType shelf_items_tab_get_type (void) {
	static volatile gsize shelf_items_tab_type_id__volatile = 0;
	if (g_once_init_enter (&shelf_items_tab_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ShelfItemsTabClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) shelf_items_tab_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ShelfItemsTab), 0, (GInstanceInitFunc) shelf_items_tab_instance_init, NULL };
		GType shelf_items_tab_type_id;
		shelf_items_tab_type_id = g_type_register_static (G_TYPE_OBJECT, "ShelfItemsTab", &g_define_type_info, 0);
		g_once_init_leave (&shelf_items_tab_type_id__volatile, shelf_items_tab_type_id);
	}
	return shelf_items_tab_type_id__volatile;
}


static void _vala_shelf_items_tab_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	ShelfItemsTab * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SHELF_ITEMS_TYPE_TAB, ShelfItemsTab);
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	switch (property_id) {
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
		case SHELF_ITEMS_TAB_TAB_MANAGER:
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
		g_value_set_object (value, shelf_items_tab_get_tab_manager (self));
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
		break;
#line 440 "Tab.c"
		default:
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
		break;
#line 446 "Tab.c"
	}
}


static void _vala_shelf_items_tab_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	ShelfItemsTab * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SHELF_ITEMS_TYPE_TAB, ShelfItemsTab);
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
	switch (property_id) {
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
		case SHELF_ITEMS_TAB_TAB_MANAGER:
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
		shelf_items_tab_set_tab_manager (self, g_value_get_object (value));
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
		break;
#line 462 "Tab.c"
		default:
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/Tab.vala"
		break;
#line 468 "Tab.c"
	}
}



