/* TabManager.c generated by valac 0.20.1.4-f5a54, the Vala compiler
 * generated from TabManager.vala, do not modify */

/**/
/*  Copyright (C) 2011-2012 Robert Dyer, Michal Hruby, Rico Tzschichholz*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <cairo.h>
#include <gdk/gdk.h>


#define SHELF_ITEMS_TYPE_TAB_MANAGER (shelf_items_tab_manager_get_type ())
#define SHELF_ITEMS_TAB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManager))
#define SHELF_ITEMS_TAB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManagerClass))
#define SHELF_ITEMS_IS_TAB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_ITEMS_TYPE_TAB_MANAGER))
#define SHELF_ITEMS_IS_TAB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_ITEMS_TYPE_TAB_MANAGER))
#define SHELF_ITEMS_TAB_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManagerClass))

typedef struct _ShelfItemsTabManager ShelfItemsTabManager;
typedef struct _ShelfItemsTabManagerClass ShelfItemsTabManagerClass;
typedef struct _ShelfItemsTabManagerPrivate ShelfItemsTabManagerPrivate;

#define SHELF_ITEMS_TYPE_TAB (shelf_items_tab_get_type ())
#define SHELF_ITEMS_TAB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_ITEMS_TYPE_TAB, ShelfItemsTab))
#define SHELF_ITEMS_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_ITEMS_TYPE_TAB, ShelfItemsTabClass))
#define SHELF_ITEMS_IS_TAB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_ITEMS_TYPE_TAB))
#define SHELF_ITEMS_IS_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_ITEMS_TYPE_TAB))
#define SHELF_ITEMS_TAB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_ITEMS_TYPE_TAB, ShelfItemsTabClass))

typedef struct _ShelfItemsTab ShelfItemsTab;
typedef struct _ShelfItemsTabClass ShelfItemsTabClass;

#define SHELF_TYPE_DOCK_CONTROLLER (shelf_dock_controller_get_type ())
#define SHELF_DOCK_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_TYPE_DOCK_CONTROLLER, ShelfDockController))
#define SHELF_DOCK_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_TYPE_DOCK_CONTROLLER, ShelfDockControllerClass))
#define SHELF_IS_DOCK_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_TYPE_DOCK_CONTROLLER))
#define SHELF_IS_DOCK_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_TYPE_DOCK_CONTROLLER))
#define SHELF_DOCK_CONTROLLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_TYPE_DOCK_CONTROLLER, ShelfDockControllerClass))

typedef struct _ShelfDockController ShelfDockController;
typedef struct _ShelfDockControllerClass ShelfDockControllerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _ShelfItemsTabPrivate ShelfItemsTabPrivate;

#define SHELF_DRAWING_TYPE_TAB_RENDERER (shelf_drawing_tab_renderer_get_type ())
#define SHELF_DRAWING_TAB_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_DRAWING_TYPE_TAB_RENDERER, ShelfDrawingTabRenderer))
#define SHELF_DRAWING_TAB_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_DRAWING_TYPE_TAB_RENDERER, ShelfDrawingTabRendererClass))
#define SHELF_DRAWING_IS_TAB_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_DRAWING_TYPE_TAB_RENDERER))
#define SHELF_DRAWING_IS_TAB_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_DRAWING_TYPE_TAB_RENDERER))
#define SHELF_DRAWING_TAB_RENDERER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_DRAWING_TYPE_TAB_RENDERER, ShelfDrawingTabRendererClass))

typedef struct _ShelfDrawingTabRenderer ShelfDrawingTabRenderer;
typedef struct _ShelfDrawingTabRendererClass ShelfDrawingTabRendererClass;

struct _ShelfItemsTabManager {
	GObject parent_instance;
	ShelfItemsTabManagerPrivate * priv;
	gint tab_icon_size;
	gint tab_margin;
};

struct _ShelfItemsTabManagerClass {
	GObjectClass parent_class;
};

struct _ShelfItemsTabManagerPrivate {
	GeeArrayList* tabs;
	GeeMap* saved_tabs_positions;
	ShelfDockController* _controller;
};

struct _ShelfItemsTab {
	GObject parent_instance;
	ShelfItemsTabPrivate * priv;
	ShelfDrawingTabRenderer* tab_renderer;
	gboolean hovered;
};

struct _ShelfItemsTabClass {
	GObjectClass parent_class;
};


static gpointer shelf_items_tab_manager_parent_class = NULL;

GType shelf_items_tab_manager_get_type (void) G_GNUC_CONST;
GType shelf_items_tab_get_type (void) G_GNUC_CONST;
GType shelf_dock_controller_get_type (void) G_GNUC_CONST;
#define SHELF_ITEMS_TAB_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManagerPrivate))
enum  {
	SHELF_ITEMS_TAB_MANAGER_DUMMY_PROPERTY,
	SHELF_ITEMS_TAB_MANAGER_CONTROLLER
};
ShelfItemsTabManager* shelf_items_tab_manager_new (ShelfDockController* controller);
ShelfItemsTabManager* shelf_items_tab_manager_construct (GType object_type, ShelfDockController* controller);
void shelf_items_tab_manager_populate (ShelfItemsTabManager* self);
void shelf_items_tab_manager_add_tab (ShelfItemsTabManager* self, ShelfItemsTab* t);
ShelfItemsTab* shelf_items_tab_new (ShelfItemsTabManager* manager);
ShelfItemsTab* shelf_items_tab_construct (GType object_type, ShelfItemsTabManager* manager);
void shelf_items_tab_manager_draw (ShelfItemsTabManager* self, cairo_t* cr);
void shelf_items_tab_draw (ShelfItemsTab* self, cairo_t* cr, gint position);
gint shelf_items_tab_manager_get_tab_position (ShelfItemsTabManager* self, ShelfItemsTab* t);
void shelf_items_tab_manager_check_tab_mouse_collision (ShelfItemsTabManager* self, GdkEventMotion* event);
gboolean shelf_items_tab_is_mouse_inside_tab (ShelfItemsTab* self, GdkEventMotion* event);
GType shelf_drawing_tab_renderer_get_type (void) G_GNUC_CONST;
static ShelfDockController* shelf_items_tab_manager_get_controller (ShelfItemsTabManager* self);
static void shelf_items_tab_manager_set_controller (ShelfItemsTabManager* self, ShelfDockController* value);
static GObject * shelf_items_tab_manager_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void shelf_items_tab_manager_finalize (GObject* obj);
static void _vala_shelf_items_tab_manager_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_shelf_items_tab_manager_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


/**
 * Creates a new item manager.
 */
ShelfItemsTabManager* shelf_items_tab_manager_construct (GType object_type, ShelfDockController* controller) {
	ShelfItemsTabManager * self = NULL;
	ShelfDockController* _tmp0_;
#line 43 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	g_return_val_if_fail (controller != NULL, NULL);
#line 45 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp0_ = controller;
#line 45 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	self = (ShelfItemsTabManager*) g_object_new (object_type, "controller", _tmp0_, NULL);
#line 43 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	return self;
#line 145 "TabManager.c"
}


ShelfItemsTabManager* shelf_items_tab_manager_new (ShelfDockController* controller) {
#line 43 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	return shelf_items_tab_manager_construct (SHELF_ITEMS_TYPE_TAB_MANAGER, controller);
#line 152 "TabManager.c"
}


/**
 * Populate the tab list with some dummy tabs.
 */
void shelf_items_tab_manager_populate (ShelfItemsTabManager* self) {
	ShelfItemsTab* _tmp0_;
	ShelfItemsTab* _tmp1_;
	ShelfItemsTab* _tmp2_;
	ShelfItemsTab* _tmp3_;
	ShelfItemsTab* _tmp4_;
	ShelfItemsTab* _tmp5_;
#line 62 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	g_return_if_fail (self != NULL);
#line 64 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp0_ = shelf_items_tab_new (self);
#line 64 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp1_ = _tmp0_;
#line 64 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	shelf_items_tab_manager_add_tab (self, _tmp1_);
#line 64 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_g_object_unref0 (_tmp1_);
#line 65 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp2_ = shelf_items_tab_new (self);
#line 65 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp3_ = _tmp2_;
#line 65 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	shelf_items_tab_manager_add_tab (self, _tmp3_);
#line 65 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_g_object_unref0 (_tmp3_);
#line 66 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp4_ = shelf_items_tab_new (self);
#line 66 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp5_ = _tmp4_;
#line 66 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	shelf_items_tab_manager_add_tab (self, _tmp5_);
#line 66 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_g_object_unref0 (_tmp5_);
#line 192 "TabManager.c"
}


void shelf_items_tab_manager_add_tab (ShelfItemsTabManager* self, ShelfItemsTab* t) {
	GeeArrayList* _tmp0_;
	ShelfItemsTab* _tmp1_;
	GeeMap* _tmp2_;
	ShelfItemsTab* _tmp3_;
	GeeArrayList* _tmp4_;
	gint _tmp5_;
	gint _tmp6_;
#line 69 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	g_return_if_fail (self != NULL);
#line 69 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	g_return_if_fail (t != NULL);
#line 71 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp0_ = self->priv->tabs;
#line 71 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp1_ = t;
#line 71 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp0_, _tmp1_);
#line 72 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp2_ = self->priv->saved_tabs_positions;
#line 72 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp3_ = t;
#line 72 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp4_ = self->priv->tabs;
#line 72 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp5_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp4_);
#line 72 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp6_ = _tmp5_;
#line 72 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	gee_map_set (_tmp2_, _tmp3_, (gpointer) ((gintptr) (_tmp6_ - 1)));
#line 226 "TabManager.c"
}


/**
 * Draws the list of tabs.
 */
static gpointer _g_object_ref0 (gpointer self) {
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	return self ? g_object_ref (self) : NULL;
#line 236 "TabManager.c"
}


void shelf_items_tab_manager_draw (ShelfItemsTabManager* self, cairo_t* cr) {
	gint i;
#line 78 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	g_return_if_fail (self != NULL);
#line 78 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	g_return_if_fail (cr != NULL);
#line 80 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	i = 0;
#line 248 "TabManager.c"
	{
		GeeArrayList* _tmp0_;
		GeeArrayList* _tmp1_;
		GeeArrayList* _t_list;
		GeeArrayList* _tmp2_;
		gint _tmp3_;
		gint _tmp4_;
		gint _t_size;
		gint _t_index;
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		_tmp0_ = self->priv->tabs;
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		_tmp1_ = _g_object_ref0 (_tmp0_);
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		_t_list = _tmp1_;
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		_tmp2_ = _t_list;
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		_tmp4_ = _tmp3_;
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		_t_size = _tmp4_;
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		_t_index = -1;
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		while (TRUE) {
#line 276 "TabManager.c"
			gint _tmp5_;
			gint _tmp6_;
			gint _tmp7_;
			GeeArrayList* _tmp8_;
			gint _tmp9_;
			gpointer _tmp10_ = NULL;
			ShelfItemsTab* t;
			ShelfItemsTab* _tmp11_;
			cairo_t* _tmp12_;
			gint _tmp13_;
			gint _tmp14_;
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp5_ = _t_index;
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_t_index = _tmp5_ + 1;
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp6_ = _t_index;
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp7_ = _t_size;
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			if (!(_tmp6_ < _tmp7_)) {
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
				break;
#line 300 "TabManager.c"
			}
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp8_ = _t_list;
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp9_ = _t_index;
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			t = (ShelfItemsTab*) _tmp10_;
#line 82 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp11_ = t;
#line 82 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp12_ = cr;
#line 82 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp13_ = i;
#line 82 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			shelf_items_tab_draw (_tmp11_, _tmp12_, _tmp13_);
#line 83 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp14_ = i;
#line 83 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			i = _tmp14_ + 1;
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_g_object_unref0 (t);
#line 324 "TabManager.c"
		}
#line 81 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		_g_object_unref0 (_t_list);
#line 328 "TabManager.c"
	}
}


gint shelf_items_tab_manager_get_tab_position (ShelfItemsTabManager* self, ShelfItemsTab* t) {
	gint result = 0;
	GeeMap* _tmp0_;
	ShelfItemsTab* _tmp1_;
	gpointer _tmp2_ = NULL;
#line 87 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 87 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	g_return_val_if_fail (t != NULL, 0);
#line 89 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp0_ = self->priv->saved_tabs_positions;
#line 89 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp1_ = t;
#line 89 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp2_ = gee_map_get (_tmp0_, _tmp1_);
#line 89 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	result = (gint) ((gintptr) _tmp2_);
#line 89 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	return result;
#line 352 "TabManager.c"
}


void shelf_items_tab_manager_check_tab_mouse_collision (ShelfItemsTabManager* self, GdkEventMotion* event) {
#line 92 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	g_return_if_fail (self != NULL);
#line 92 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	g_return_if_fail (event != NULL);
#line 361 "TabManager.c"
	{
		GeeArrayList* _tmp0_;
		GeeArrayList* _tmp1_;
		GeeArrayList* _t_list;
		GeeArrayList* _tmp2_;
		gint _tmp3_;
		gint _tmp4_;
		gint _t_size;
		gint _t_index;
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		_tmp0_ = self->priv->tabs;
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		_tmp1_ = _g_object_ref0 (_tmp0_);
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		_t_list = _tmp1_;
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		_tmp2_ = _t_list;
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		_tmp4_ = _tmp3_;
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		_t_size = _tmp4_;
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		_t_index = -1;
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		while (TRUE) {
#line 389 "TabManager.c"
			gint _tmp5_;
			gint _tmp6_;
			gint _tmp7_;
			GeeArrayList* _tmp8_;
			gint _tmp9_;
			gpointer _tmp10_ = NULL;
			ShelfItemsTab* t;
			ShelfItemsTab* _tmp11_;
			ShelfItemsTab* _tmp12_;
			GdkEventMotion _tmp13_;
			gboolean _tmp14_ = FALSE;
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp5_ = _t_index;
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_t_index = _tmp5_ + 1;
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp6_ = _t_index;
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp7_ = _t_size;
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			if (!(_tmp6_ < _tmp7_)) {
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
				break;
#line 413 "TabManager.c"
			}
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp8_ = _t_list;
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp9_ = _t_index;
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			t = (ShelfItemsTab*) _tmp10_;
#line 95 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp11_ = t;
#line 95 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp12_ = t;
#line 95 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp13_ = *event;
#line 95 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp14_ = shelf_items_tab_is_mouse_inside_tab (_tmp12_, &_tmp13_);
#line 95 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_tmp11_->hovered = _tmp14_;
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
			_g_object_unref0 (t);
#line 435 "TabManager.c"
		}
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		_g_object_unref0 (_t_list);
#line 439 "TabManager.c"
	}
}


static ShelfDockController* shelf_items_tab_manager_get_controller (ShelfItemsTabManager* self) {
	ShelfDockController* result;
	ShelfDockController* _tmp0_;
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp0_ = self->priv->_controller;
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	result = _tmp0_;
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	return result;
#line 455 "TabManager.c"
}


static void shelf_items_tab_manager_set_controller (ShelfItemsTabManager* self, ShelfDockController* value) {
	ShelfDockController* _tmp0_;
	ShelfDockController* _tmp1_;
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	g_return_if_fail (self != NULL);
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp0_ = value;
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_g_object_unref0 (self->priv->_controller);
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	self->priv->_controller = _tmp1_;
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	g_object_notify ((GObject *) self, "controller");
#line 474 "TabManager.c"
}


static GObject * shelf_items_tab_manager_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	ShelfItemsTabManager * self;
	GeeArrayList* _tmp0_;
	GeeHashMap* _tmp1_;
#line 48 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	parent_class = G_OBJECT_CLASS (shelf_items_tab_manager_parent_class);
#line 48 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 48 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManager);
#line 50 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp0_ = gee_array_list_new (SHELF_ITEMS_TYPE_TAB, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
#line 50 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_g_object_unref0 (self->priv->tabs);
#line 50 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	self->priv->tabs = _tmp0_;
#line 51 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_tmp1_ = gee_hash_map_new (SHELF_ITEMS_TYPE_TAB, (GBoxedCopyFunc) g_object_ref, g_object_unref, G_TYPE_INT, NULL, NULL, NULL, NULL, NULL);
#line 51 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_g_object_unref0 (self->priv->saved_tabs_positions);
#line 51 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	self->priv->saved_tabs_positions = (GeeMap*) _tmp1_;
#line 52 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	shelf_items_tab_manager_populate (self);
#line 48 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	return obj;
#line 506 "TabManager.c"
}


static void shelf_items_tab_manager_class_init (ShelfItemsTabManagerClass * klass) {
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	shelf_items_tab_manager_parent_class = g_type_class_peek_parent (klass);
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	g_type_class_add_private (klass, sizeof (ShelfItemsTabManagerPrivate));
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_shelf_items_tab_manager_get_property;
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_shelf_items_tab_manager_set_property;
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	G_OBJECT_CLASS (klass)->constructor = shelf_items_tab_manager_constructor;
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	G_OBJECT_CLASS (klass)->finalize = shelf_items_tab_manager_finalize;
#line 523 "TabManager.c"
	/**
	 * The controller for this dock.
	 */
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SHELF_ITEMS_TAB_MANAGER_CONTROLLER, g_param_spec_object ("controller", "controller", "controller", SHELF_TYPE_DOCK_CONTROLLER, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 529 "TabManager.c"
}


static void shelf_items_tab_manager_instance_init (ShelfItemsTabManager * self) {
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	self->priv = SHELF_ITEMS_TAB_MANAGER_GET_PRIVATE (self);
#line 33 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	self->tab_icon_size = 48;
#line 34 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	self->tab_margin = 8;
#line 540 "TabManager.c"
}


static void shelf_items_tab_manager_finalize (GObject* obj) {
	ShelfItemsTabManager * self;
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManager);
#line 29 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_g_object_unref0 (self->priv->tabs);
#line 30 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_g_object_unref0 (self->priv->saved_tabs_positions);
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	_g_object_unref0 (self->priv->_controller);
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	G_OBJECT_CLASS (shelf_items_tab_manager_parent_class)->finalize (obj);
#line 556 "TabManager.c"
}


/**
 * The main manager for dock tabs.
 */
GType shelf_items_tab_manager_get_type (void) {
	static volatile gsize shelf_items_tab_manager_type_id__volatile = 0;
	if (g_once_init_enter (&shelf_items_tab_manager_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ShelfItemsTabManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) shelf_items_tab_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ShelfItemsTabManager), 0, (GInstanceInitFunc) shelf_items_tab_manager_instance_init, NULL };
		GType shelf_items_tab_manager_type_id;
		shelf_items_tab_manager_type_id = g_type_register_static (G_TYPE_OBJECT, "ShelfItemsTabManager", &g_define_type_info, 0);
		g_once_init_leave (&shelf_items_tab_manager_type_id__volatile, shelf_items_tab_manager_type_id);
	}
	return shelf_items_tab_manager_type_id__volatile;
}


static void _vala_shelf_items_tab_manager_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	ShelfItemsTabManager * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManager);
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	switch (property_id) {
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		case SHELF_ITEMS_TAB_MANAGER_CONTROLLER:
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		g_value_set_object (value, shelf_items_tab_manager_get_controller (self));
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		break;
#line 586 "TabManager.c"
		default:
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		break;
#line 592 "TabManager.c"
	}
}


static void _vala_shelf_items_tab_manager_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	ShelfItemsTabManager * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManager);
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
	switch (property_id) {
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		case SHELF_ITEMS_TAB_MANAGER_CONTROLLER:
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		shelf_items_tab_manager_set_controller (self, g_value_get_object (value));
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		break;
#line 608 "TabManager.c"
		default:
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/lib/Items/TabManager.vala"
		break;
#line 614 "TabManager.c"
	}
}



