/* DockPositionManager.c generated by valac 0.20.1.4-f5a54, the Vala compiler
 * generated from DockPositionManager.vala, do not modify */

/**/
/*  Copyright (C) 2011-2012 Robert Dyer, Michal Hruby, Rico Tzschichholz*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER (shelf_system_dock_position_manager_get_type ())
#define SHELF_SYSTEM_DOCK_POSITION_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER, ShelfSystemDockPositionManager))
#define SHELF_SYSTEM_DOCK_POSITION_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER, ShelfSystemDockPositionManagerClass))
#define SHELF_SYSTEM_IS_DOCK_POSITION_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER))
#define SHELF_SYSTEM_IS_DOCK_POSITION_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER))
#define SHELF_SYSTEM_DOCK_POSITION_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER, ShelfSystemDockPositionManagerClass))

typedef struct _ShelfSystemDockPositionManager ShelfSystemDockPositionManager;
typedef struct _ShelfSystemDockPositionManagerClass ShelfSystemDockPositionManagerClass;
typedef struct _ShelfSystemDockPositionManagerPrivate ShelfSystemDockPositionManagerPrivate;

#define SHELF_TYPE_DOCK_CONTROLLER (shelf_dock_controller_get_type ())
#define SHELF_DOCK_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_TYPE_DOCK_CONTROLLER, ShelfDockController))
#define SHELF_DOCK_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_TYPE_DOCK_CONTROLLER, ShelfDockControllerClass))
#define SHELF_IS_DOCK_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_TYPE_DOCK_CONTROLLER))
#define SHELF_IS_DOCK_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_TYPE_DOCK_CONTROLLER))
#define SHELF_DOCK_CONTROLLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_TYPE_DOCK_CONTROLLER, ShelfDockControllerClass))

typedef struct _ShelfDockController ShelfDockController;
typedef struct _ShelfDockControllerClass ShelfDockControllerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _ShelfDockControllerPrivate ShelfDockControllerPrivate;

#define SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW (shelf_widgets_composited_window_get_type ())
#define SHELF_WIDGETS_COMPOSITED_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW, ShelfWidgetsCompositedWindow))
#define SHELF_WIDGETS_COMPOSITED_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW, ShelfWidgetsCompositedWindowClass))
#define SHELF_WIDGETS_IS_COMPOSITED_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW))
#define SHELF_WIDGETS_IS_COMPOSITED_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW))
#define SHELF_WIDGETS_COMPOSITED_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW, ShelfWidgetsCompositedWindowClass))

typedef struct _ShelfWidgetsCompositedWindow ShelfWidgetsCompositedWindow;
typedef struct _ShelfWidgetsCompositedWindowClass ShelfWidgetsCompositedWindowClass;

#define SHELF_WIDGETS_TYPE_DOCK_WINDOW (shelf_widgets_dock_window_get_type ())
#define SHELF_WIDGETS_DOCK_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_WIDGETS_TYPE_DOCK_WINDOW, ShelfWidgetsDockWindow))
#define SHELF_WIDGETS_DOCK_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_WIDGETS_TYPE_DOCK_WINDOW, ShelfWidgetsDockWindowClass))
#define SHELF_WIDGETS_IS_DOCK_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_WIDGETS_TYPE_DOCK_WINDOW))
#define SHELF_WIDGETS_IS_DOCK_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_WIDGETS_TYPE_DOCK_WINDOW))
#define SHELF_WIDGETS_DOCK_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_WIDGETS_TYPE_DOCK_WINDOW, ShelfWidgetsDockWindowClass))

typedef struct _ShelfWidgetsDockWindow ShelfWidgetsDockWindow;
typedef struct _ShelfWidgetsDockWindowClass ShelfWidgetsDockWindowClass;

#define SHELF_DRAWING_TYPE_DOCK_RENDERER (shelf_drawing_dock_renderer_get_type ())
#define SHELF_DRAWING_DOCK_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_DRAWING_TYPE_DOCK_RENDERER, ShelfDrawingDockRenderer))
#define SHELF_DRAWING_DOCK_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_DRAWING_TYPE_DOCK_RENDERER, ShelfDrawingDockRendererClass))
#define SHELF_DRAWING_IS_DOCK_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_DRAWING_TYPE_DOCK_RENDERER))
#define SHELF_DRAWING_IS_DOCK_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_DRAWING_TYPE_DOCK_RENDERER))
#define SHELF_DRAWING_DOCK_RENDERER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_DRAWING_TYPE_DOCK_RENDERER, ShelfDrawingDockRendererClass))

typedef struct _ShelfDrawingDockRenderer ShelfDrawingDockRenderer;
typedef struct _ShelfDrawingDockRendererClass ShelfDrawingDockRendererClass;

#define SHELF_ITEMS_TYPE_TAB_MANAGER (shelf_items_tab_manager_get_type ())
#define SHELF_ITEMS_TAB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManager))
#define SHELF_ITEMS_TAB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManagerClass))
#define SHELF_ITEMS_IS_TAB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_ITEMS_TYPE_TAB_MANAGER))
#define SHELF_ITEMS_IS_TAB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_ITEMS_TYPE_TAB_MANAGER))
#define SHELF_ITEMS_TAB_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManagerClass))

typedef struct _ShelfItemsTabManager ShelfItemsTabManager;
typedef struct _ShelfItemsTabManagerClass ShelfItemsTabManagerClass;

struct _ShelfSystemDockPositionManager {
	GObject parent_instance;
	ShelfSystemDockPositionManagerPrivate * priv;
};

struct _ShelfSystemDockPositionManagerClass {
	GObjectClass parent_class;
};

struct _ShelfSystemDockPositionManagerPrivate {
	ShelfDockController* _controller;
};

struct _ShelfDockController {
	GObject parent_instance;
	ShelfDockControllerPrivate * priv;
	ShelfWidgetsDockWindow* window;
	ShelfDrawingDockRenderer* renderer;
	ShelfSystemDockPositionManager* position_manager;
	ShelfItemsTabManager* tab_manager;
};

struct _ShelfDockControllerClass {
	GObjectClass parent_class;
};


static gpointer shelf_system_dock_position_manager_parent_class = NULL;

GType shelf_system_dock_position_manager_get_type (void) G_GNUC_CONST;
GType shelf_dock_controller_get_type (void) G_GNUC_CONST;
#define SHELF_SYSTEM_DOCK_POSITION_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER, ShelfSystemDockPositionManagerPrivate))
enum  {
	SHELF_SYSTEM_DOCK_POSITION_MANAGER_DUMMY_PROPERTY,
	SHELF_SYSTEM_DOCK_POSITION_MANAGER_CONTROLLER
};
ShelfSystemDockPositionManager* shelf_system_dock_position_manager_new (ShelfDockController* controller);
ShelfSystemDockPositionManager* shelf_system_dock_position_manager_construct (GType object_type, ShelfDockController* controller);
void shelf_system_dock_position_manager_initialize (ShelfSystemDockPositionManager* self);
static ShelfDockController* shelf_system_dock_position_manager_get_controller (ShelfSystemDockPositionManager* self);
GType shelf_widgets_composited_window_get_type (void) G_GNUC_CONST;
GType shelf_widgets_dock_window_get_type (void) G_GNUC_CONST;
GType shelf_drawing_dock_renderer_get_type (void) G_GNUC_CONST;
GType shelf_items_tab_manager_get_type (void) G_GNUC_CONST;
static void shelf_system_dock_position_manager_set_controller (ShelfSystemDockPositionManager* self, ShelfDockController* value);
static GObject * shelf_system_dock_position_manager_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void shelf_system_dock_position_manager_finalize (GObject* obj);
static void _vala_shelf_system_dock_position_manager_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_shelf_system_dock_position_manager_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


/**
 * Creates a new position manager.
 */
ShelfSystemDockPositionManager* shelf_system_dock_position_manager_construct (GType object_type, ShelfDockController* controller) {
	ShelfSystemDockPositionManager * self = NULL;
	ShelfDockController* _tmp0_;
#line 33 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	g_return_val_if_fail (controller != NULL, NULL);
#line 35 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	_tmp0_ = controller;
#line 35 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	self = (ShelfSystemDockPositionManager*) g_object_new (object_type, "controller", _tmp0_, NULL);
#line 33 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	return self;
#line 155 "DockPositionManager.c"
}


ShelfSystemDockPositionManager* shelf_system_dock_position_manager_new (ShelfDockController* controller) {
#line 33 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	return shelf_system_dock_position_manager_construct (SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER, controller);
#line 162 "DockPositionManager.c"
}


void shelf_system_dock_position_manager_initialize (ShelfSystemDockPositionManager* self) {
	ShelfDockController* _tmp0_;
	ShelfWidgetsDockWindow* _tmp1_;
#line 46 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	g_return_if_fail (self != NULL);
#line 48 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	_tmp0_ = self->priv->_controller;
#line 48 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	_tmp1_ = _tmp0_->window;
#line 48 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	gtk_window_move ((GtkWindow*) _tmp1_, 100, 100);
#line 177 "DockPositionManager.c"
}


static ShelfDockController* shelf_system_dock_position_manager_get_controller (ShelfSystemDockPositionManager* self) {
	ShelfDockController* result;
	ShelfDockController* _tmp0_;
#line 28 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 28 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	_tmp0_ = self->priv->_controller;
#line 28 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	result = _tmp0_;
#line 28 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	return result;
#line 192 "DockPositionManager.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 28 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	return self ? g_object_ref (self) : NULL;
#line 199 "DockPositionManager.c"
}


static void shelf_system_dock_position_manager_set_controller (ShelfSystemDockPositionManager* self, ShelfDockController* value) {
	ShelfDockController* _tmp0_;
	ShelfDockController* _tmp1_;
#line 28 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	g_return_if_fail (self != NULL);
#line 28 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	_tmp0_ = value;
#line 28 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 28 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	_g_object_unref0 (self->priv->_controller);
#line 28 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	self->priv->_controller = _tmp1_;
#line 28 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	g_object_notify ((GObject *) self, "controller");
#line 218 "DockPositionManager.c"
}


static GObject * shelf_system_dock_position_manager_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	ShelfSystemDockPositionManager * self;
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	parent_class = G_OBJECT_CLASS (shelf_system_dock_position_manager_parent_class);
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER, ShelfSystemDockPositionManager);
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	return obj;
#line 234 "DockPositionManager.c"
}


static void shelf_system_dock_position_manager_class_init (ShelfSystemDockPositionManagerClass * klass) {
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	shelf_system_dock_position_manager_parent_class = g_type_class_peek_parent (klass);
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	g_type_class_add_private (klass, sizeof (ShelfSystemDockPositionManagerPrivate));
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_shelf_system_dock_position_manager_get_property;
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_shelf_system_dock_position_manager_set_property;
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	G_OBJECT_CLASS (klass)->constructor = shelf_system_dock_position_manager_constructor;
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	G_OBJECT_CLASS (klass)->finalize = shelf_system_dock_position_manager_finalize;
#line 251 "DockPositionManager.c"
	/**
	 * The controller for this dock.
	 */
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SHELF_SYSTEM_DOCK_POSITION_MANAGER_CONTROLLER, g_param_spec_object ("controller", "controller", "controller", SHELF_TYPE_DOCK_CONTROLLER, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 257 "DockPositionManager.c"
}


static void shelf_system_dock_position_manager_instance_init (ShelfSystemDockPositionManager * self) {
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	self->priv = SHELF_SYSTEM_DOCK_POSITION_MANAGER_GET_PRIVATE (self);
#line 264 "DockPositionManager.c"
}


static void shelf_system_dock_position_manager_finalize (GObject* obj) {
	ShelfSystemDockPositionManager * self;
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER, ShelfSystemDockPositionManager);
#line 28 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	_g_object_unref0 (self->priv->_controller);
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	G_OBJECT_CLASS (shelf_system_dock_position_manager_parent_class)->finalize (obj);
#line 276 "DockPositionManager.c"
}


/**
 * The main position manager for the dock.
 */
GType shelf_system_dock_position_manager_get_type (void) {
	static volatile gsize shelf_system_dock_position_manager_type_id__volatile = 0;
	if (g_once_init_enter (&shelf_system_dock_position_manager_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ShelfSystemDockPositionManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) shelf_system_dock_position_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ShelfSystemDockPositionManager), 0, (GInstanceInitFunc) shelf_system_dock_position_manager_instance_init, NULL };
		GType shelf_system_dock_position_manager_type_id;
		shelf_system_dock_position_manager_type_id = g_type_register_static (G_TYPE_OBJECT, "ShelfSystemDockPositionManager", &g_define_type_info, 0);
		g_once_init_leave (&shelf_system_dock_position_manager_type_id__volatile, shelf_system_dock_position_manager_type_id);
	}
	return shelf_system_dock_position_manager_type_id__volatile;
}


static void _vala_shelf_system_dock_position_manager_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	ShelfSystemDockPositionManager * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER, ShelfSystemDockPositionManager);
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	switch (property_id) {
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
		case SHELF_SYSTEM_DOCK_POSITION_MANAGER_CONTROLLER:
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
		g_value_set_object (value, shelf_system_dock_position_manager_get_controller (self));
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
		break;
#line 306 "DockPositionManager.c"
		default:
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
		break;
#line 312 "DockPositionManager.c"
	}
}


static void _vala_shelf_system_dock_position_manager_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	ShelfSystemDockPositionManager * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER, ShelfSystemDockPositionManager);
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
	switch (property_id) {
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
		case SHELF_SYSTEM_DOCK_POSITION_MANAGER_CONTROLLER:
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
		shelf_system_dock_position_manager_set_controller (self, g_value_get_object (value));
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
		break;
#line 328 "DockPositionManager.c"
		default:
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/System/DockPositionManager.vala"
		break;
#line 334 "DockPositionManager.c"
	}
}



