/* TabRenderer.c generated by valac 0.20.1.4-f5a54, the Vala compiler
 * generated from TabRenderer.vala, do not modify */

/**/
/*  Copyright (C) 2011-2012 Robert Dyer, Michal Hruby, Rico Tzschichholz*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include <cairo.h>
#include <float.h>
#include <math.h>


#define SHELF_DRAWING_TYPE_TAB_RENDERER (shelf_drawing_tab_renderer_get_type ())
#define SHELF_DRAWING_TAB_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_DRAWING_TYPE_TAB_RENDERER, ShelfDrawingTabRenderer))
#define SHELF_DRAWING_TAB_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_DRAWING_TYPE_TAB_RENDERER, ShelfDrawingTabRendererClass))
#define SHELF_DRAWING_IS_TAB_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_DRAWING_TYPE_TAB_RENDERER))
#define SHELF_DRAWING_IS_TAB_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_DRAWING_TYPE_TAB_RENDERER))
#define SHELF_DRAWING_TAB_RENDERER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_DRAWING_TYPE_TAB_RENDERER, ShelfDrawingTabRendererClass))

typedef struct _ShelfDrawingTabRenderer ShelfDrawingTabRenderer;
typedef struct _ShelfDrawingTabRendererClass ShelfDrawingTabRendererClass;
typedef struct _ShelfDrawingTabRendererPrivate ShelfDrawingTabRendererPrivate;

struct _ShelfDrawingTabRenderer {
	GObject parent_instance;
	ShelfDrawingTabRendererPrivate * priv;
};

struct _ShelfDrawingTabRendererClass {
	GObjectClass parent_class;
};


static gpointer shelf_drawing_tab_renderer_parent_class = NULL;

GType shelf_drawing_tab_renderer_get_type (void) G_GNUC_CONST;
enum  {
	SHELF_DRAWING_TAB_RENDERER_DUMMY_PROPERTY
};
ShelfDrawingTabRenderer* shelf_drawing_tab_renderer_new (void);
ShelfDrawingTabRenderer* shelf_drawing_tab_renderer_construct (GType object_type);
void shelf_drawing_tab_renderer_draw (ShelfDrawingTabRenderer* self, cairo_t* cr, gint position);
static GObject * shelf_drawing_tab_renderer_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void shelf_drawing_tab_renderer_finalize (GObject* obj);


/**
 * Creates a new tab renderer.
 */
ShelfDrawingTabRenderer* shelf_drawing_tab_renderer_construct (GType object_type) {
	ShelfDrawingTabRenderer * self = NULL;
#line 31 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	self = (ShelfDrawingTabRenderer*) g_object_new (object_type, NULL);
#line 29 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	return self;
#line 72 "TabRenderer.c"
}


ShelfDrawingTabRenderer* shelf_drawing_tab_renderer_new (void) {
#line 29 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	return shelf_drawing_tab_renderer_construct (SHELF_DRAWING_TYPE_TAB_RENDERER);
#line 79 "TabRenderer.c"
}


/**
 * Draws a tab.
 */
void shelf_drawing_tab_renderer_draw (ShelfDrawingTabRenderer* self, cairo_t* cr, gint position) {
	gint icon_size;
	gint _tmp0_;
	gint vertical_offset;
	cairo_t* _tmp1_;
	cairo_t* _tmp2_;
	cairo_t* _tmp3_;
	cairo_t* _tmp4_;
	cairo_t* _tmp5_;
	cairo_t* _tmp6_;
	cairo_t* _tmp7_;
	cairo_t* _tmp8_;
	cairo_t* _tmp9_;
#line 45 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	g_return_if_fail (self != NULL);
#line 45 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	g_return_if_fail (cr != NULL);
#line 47 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	icon_size = 48;
#line 48 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	_tmp0_ = position;
#line 48 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	vertical_offset = icon_size * _tmp0_;
#line 49 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	_tmp1_ = cr;
#line 49 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	cairo_save (_tmp1_);
#line 51 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	_tmp2_ = cr;
#line 51 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	cairo_move_to (_tmp2_, (gdouble) 0, (gdouble) vertical_offset);
#line 52 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	_tmp3_ = cr;
#line 52 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	cairo_rel_line_to (_tmp3_, (gdouble) icon_size, (gdouble) 0);
#line 53 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	_tmp4_ = cr;
#line 53 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	cairo_rel_line_to (_tmp4_, (gdouble) 0, (gdouble) icon_size);
#line 54 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	_tmp5_ = cr;
#line 54 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	cairo_rel_line_to (_tmp5_, (gdouble) (-icon_size), (gdouble) 0);
#line 55 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	_tmp6_ = cr;
#line 55 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	cairo_close_path (_tmp6_);
#line 57 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	_tmp7_ = cr;
#line 57 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	cairo_stroke (_tmp7_);
#line 58 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	_tmp8_ = cr;
#line 58 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	cairo_fill (_tmp8_);
#line 60 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	_tmp9_ = cr;
#line 60 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	cairo_restore (_tmp9_);
#line 145 "TabRenderer.c"
}


static GObject * shelf_drawing_tab_renderer_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	ShelfDrawingTabRenderer * self;
#line 34 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	parent_class = G_OBJECT_CLASS (shelf_drawing_tab_renderer_parent_class);
#line 34 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 34 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHELF_DRAWING_TYPE_TAB_RENDERER, ShelfDrawingTabRenderer);
#line 34 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	return obj;
#line 161 "TabRenderer.c"
}


static void shelf_drawing_tab_renderer_class_init (ShelfDrawingTabRendererClass * klass) {
#line 24 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	shelf_drawing_tab_renderer_parent_class = g_type_class_peek_parent (klass);
#line 24 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	G_OBJECT_CLASS (klass)->constructor = shelf_drawing_tab_renderer_constructor;
#line 24 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	G_OBJECT_CLASS (klass)->finalize = shelf_drawing_tab_renderer_finalize;
#line 172 "TabRenderer.c"
}


static void shelf_drawing_tab_renderer_instance_init (ShelfDrawingTabRenderer * self) {
}


static void shelf_drawing_tab_renderer_finalize (GObject* obj) {
	ShelfDrawingTabRenderer * self;
#line 24 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHELF_DRAWING_TYPE_TAB_RENDERER, ShelfDrawingTabRenderer);
#line 24 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/Drawing/TabRenderer.vala"
	G_OBJECT_CLASS (shelf_drawing_tab_renderer_parent_class)->finalize (obj);
#line 186 "TabRenderer.c"
}


/**
 * The main manager for dock items.
 */
GType shelf_drawing_tab_renderer_get_type (void) {
	static volatile gsize shelf_drawing_tab_renderer_type_id__volatile = 0;
	if (g_once_init_enter (&shelf_drawing_tab_renderer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ShelfDrawingTabRendererClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) shelf_drawing_tab_renderer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ShelfDrawingTabRenderer), 0, (GInstanceInitFunc) shelf_drawing_tab_renderer_instance_init, NULL };
		GType shelf_drawing_tab_renderer_type_id;
		shelf_drawing_tab_renderer_type_id = g_type_register_static (G_TYPE_OBJECT, "ShelfDrawingTabRenderer", &g_define_type_info, 0);
		g_once_init_leave (&shelf_drawing_tab_renderer_type_id__volatile, shelf_drawing_tab_renderer_type_id);
	}
	return shelf_drawing_tab_renderer_type_id__volatile;
}



