/* Factory.c generated by valac 0.20.1.4-f5a54, the Vala compiler
 * generated from Factory.vala, do not modify */

/**/
/*  Copyright (C) 2011 Robert Dyer*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>


#define SHELF_FACTORIES_TYPE_FACTORY (shelf_factories_factory_get_type ())
#define SHELF_FACTORIES_FACTORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_FACTORIES_TYPE_FACTORY, ShelfFactoriesFactory))
#define SHELF_FACTORIES_FACTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_FACTORIES_TYPE_FACTORY, ShelfFactoriesFactoryClass))
#define SHELF_FACTORIES_IS_FACTORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_FACTORIES_TYPE_FACTORY))
#define SHELF_FACTORIES_IS_FACTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_FACTORIES_TYPE_FACTORY))
#define SHELF_FACTORIES_FACTORY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_FACTORIES_TYPE_FACTORY, ShelfFactoriesFactoryClass))

typedef struct _ShelfFactoriesFactory ShelfFactoriesFactory;
typedef struct _ShelfFactoriesFactoryClass ShelfFactoriesFactoryClass;
typedef struct _ShelfFactoriesFactoryPrivate ShelfFactoriesFactoryPrivate;

#define SHELF_FACTORIES_TYPE_ABSTRACT_MAIN (shelf_factories_abstract_main_get_type ())
#define SHELF_FACTORIES_ABSTRACT_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_FACTORIES_TYPE_ABSTRACT_MAIN, ShelfFactoriesAbstractMain))
#define SHELF_FACTORIES_ABSTRACT_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_FACTORIES_TYPE_ABSTRACT_MAIN, ShelfFactoriesAbstractMainClass))
#define SHELF_FACTORIES_IS_ABSTRACT_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_FACTORIES_TYPE_ABSTRACT_MAIN))
#define SHELF_FACTORIES_IS_ABSTRACT_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_FACTORIES_TYPE_ABSTRACT_MAIN))
#define SHELF_FACTORIES_ABSTRACT_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_FACTORIES_TYPE_ABSTRACT_MAIN, ShelfFactoriesAbstractMainClass))

typedef struct _ShelfFactoriesAbstractMain ShelfFactoriesAbstractMain;
typedef struct _ShelfFactoriesAbstractMainClass ShelfFactoriesAbstractMainClass;

#define SHELF_FACTORIES_TYPE_ITEM_FACTORY (shelf_factories_item_factory_get_type ())
#define SHELF_FACTORIES_ITEM_FACTORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_FACTORIES_TYPE_ITEM_FACTORY, ShelfFactoriesItemFactory))
#define SHELF_FACTORIES_ITEM_FACTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_FACTORIES_TYPE_ITEM_FACTORY, ShelfFactoriesItemFactoryClass))
#define SHELF_FACTORIES_IS_ITEM_FACTORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_FACTORIES_TYPE_ITEM_FACTORY))
#define SHELF_FACTORIES_IS_ITEM_FACTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_FACTORIES_TYPE_ITEM_FACTORY))
#define SHELF_FACTORIES_ITEM_FACTORY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_FACTORIES_TYPE_ITEM_FACTORY, ShelfFactoriesItemFactoryClass))

typedef struct _ShelfFactoriesItemFactory ShelfFactoriesItemFactory;
typedef struct _ShelfFactoriesItemFactoryClass ShelfFactoriesItemFactoryClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _ShelfFactoriesFactory {
	GObject parent_instance;
	ShelfFactoriesFactoryPrivate * priv;
};

struct _ShelfFactoriesFactoryClass {
	GObjectClass parent_class;
};


static gpointer shelf_factories_factory_parent_class = NULL;
extern ShelfFactoriesAbstractMain* shelf_factories_factory_main;
ShelfFactoriesAbstractMain* shelf_factories_factory_main = NULL;
extern ShelfFactoriesItemFactory* shelf_factories_factory_item_factory;
ShelfFactoriesItemFactory* shelf_factories_factory_item_factory = NULL;

GType shelf_factories_factory_get_type (void) G_GNUC_CONST;
enum  {
	SHELF_FACTORIES_FACTORY_DUMMY_PROPERTY
};
GType shelf_factories_abstract_main_get_type (void) G_GNUC_CONST;
GType shelf_factories_item_factory_get_type (void) G_GNUC_CONST;
void shelf_factories_factory_init (ShelfFactoriesAbstractMain* main_class, ShelfFactoriesItemFactory* item);
ShelfFactoriesFactory* shelf_factories_factory_new (void);
ShelfFactoriesFactory* shelf_factories_factory_construct (GType object_type);
static void shelf_factories_factory_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
#line 37 "/home/gwen/Programmation/vala/vala-sandbox/lib/Factories/Factory.vala"
	return self ? g_object_ref (self) : NULL;
#line 89 "Factory.c"
}


void shelf_factories_factory_init (ShelfFactoriesAbstractMain* main_class, ShelfFactoriesItemFactory* item) {
	ShelfFactoriesAbstractMain* _tmp0_;
	ShelfFactoriesAbstractMain* _tmp1_;
	ShelfFactoriesItemFactory* _tmp2_;
	ShelfFactoriesItemFactory* _tmp3_;
#line 35 "/home/gwen/Programmation/vala/vala-sandbox/lib/Factories/Factory.vala"
	g_return_if_fail (main_class != NULL);
#line 35 "/home/gwen/Programmation/vala/vala-sandbox/lib/Factories/Factory.vala"
	g_return_if_fail (item != NULL);
#line 37 "/home/gwen/Programmation/vala/vala-sandbox/lib/Factories/Factory.vala"
	_tmp0_ = main_class;
#line 37 "/home/gwen/Programmation/vala/vala-sandbox/lib/Factories/Factory.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 37 "/home/gwen/Programmation/vala/vala-sandbox/lib/Factories/Factory.vala"
	_g_object_unref0 (shelf_factories_factory_main);
#line 37 "/home/gwen/Programmation/vala/vala-sandbox/lib/Factories/Factory.vala"
	shelf_factories_factory_main = _tmp1_;
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/Factories/Factory.vala"
	_tmp2_ = item;
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/Factories/Factory.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/Factories/Factory.vala"
	_g_object_unref0 (shelf_factories_factory_item_factory);
#line 38 "/home/gwen/Programmation/vala/vala-sandbox/lib/Factories/Factory.vala"
	shelf_factories_factory_item_factory = _tmp3_;
#line 118 "Factory.c"
}


ShelfFactoriesFactory* shelf_factories_factory_construct (GType object_type) {
	ShelfFactoriesFactory * self = NULL;
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/Factories/Factory.vala"
	self = (ShelfFactoriesFactory*) g_object_new (object_type, NULL);
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/Factories/Factory.vala"
	return self;
#line 128 "Factory.c"
}


ShelfFactoriesFactory* shelf_factories_factory_new (void) {
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/Factories/Factory.vala"
	return shelf_factories_factory_construct (SHELF_FACTORIES_TYPE_FACTORY);
#line 135 "Factory.c"
}


static void shelf_factories_factory_class_init (ShelfFactoriesFactoryClass * klass) {
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/Factories/Factory.vala"
	shelf_factories_factory_parent_class = g_type_class_peek_parent (klass);
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/Factories/Factory.vala"
	G_OBJECT_CLASS (klass)->finalize = shelf_factories_factory_finalize;
#line 144 "Factory.c"
}


static void shelf_factories_factory_instance_init (ShelfFactoriesFactory * self) {
}


static void shelf_factories_factory_finalize (GObject* obj) {
	ShelfFactoriesFactory * self;
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/Factories/Factory.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHELF_FACTORIES_TYPE_FACTORY, ShelfFactoriesFactory);
#line 23 "/home/gwen/Programmation/vala/vala-sandbox/lib/Factories/Factory.vala"
	G_OBJECT_CLASS (shelf_factories_factory_parent_class)->finalize (obj);
#line 158 "Factory.c"
}


/**
 * The main factory class for the dock.
 */
GType shelf_factories_factory_get_type (void) {
	static volatile gsize shelf_factories_factory_type_id__volatile = 0;
	if (g_once_init_enter (&shelf_factories_factory_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ShelfFactoriesFactoryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) shelf_factories_factory_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ShelfFactoriesFactory), 0, (GInstanceInitFunc) shelf_factories_factory_instance_init, NULL };
		GType shelf_factories_factory_type_id;
		shelf_factories_factory_type_id = g_type_register_static (G_TYPE_OBJECT, "ShelfFactoriesFactory", &g_define_type_info, 0);
		g_once_init_leave (&shelf_factories_factory_type_id__volatile, shelf_factories_factory_type_id);
	}
	return shelf_factories_factory_type_id__volatile;
}



