/* DockController.c generated by valac 0.20.1.4-f5a54, the Vala compiler
 * generated from DockController.vala, do not modify */

/**/
/*  Copyright (C) 2011 Robert Dyer*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define SHELF_TYPE_DOCK_CONTROLLER (shelf_dock_controller_get_type ())
#define SHELF_DOCK_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_TYPE_DOCK_CONTROLLER, ShelfDockController))
#define SHELF_DOCK_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_TYPE_DOCK_CONTROLLER, ShelfDockControllerClass))
#define SHELF_IS_DOCK_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_TYPE_DOCK_CONTROLLER))
#define SHELF_IS_DOCK_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_TYPE_DOCK_CONTROLLER))
#define SHELF_DOCK_CONTROLLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_TYPE_DOCK_CONTROLLER, ShelfDockControllerClass))

typedef struct _ShelfDockController ShelfDockController;
typedef struct _ShelfDockControllerClass ShelfDockControllerClass;
typedef struct _ShelfDockControllerPrivate ShelfDockControllerPrivate;

#define SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW (shelf_widgets_composited_window_get_type ())
#define SHELF_WIDGETS_COMPOSITED_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW, ShelfWidgetsCompositedWindow))
#define SHELF_WIDGETS_COMPOSITED_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW, ShelfWidgetsCompositedWindowClass))
#define SHELF_WIDGETS_IS_COMPOSITED_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW))
#define SHELF_WIDGETS_IS_COMPOSITED_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW))
#define SHELF_WIDGETS_COMPOSITED_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW, ShelfWidgetsCompositedWindowClass))

typedef struct _ShelfWidgetsCompositedWindow ShelfWidgetsCompositedWindow;
typedef struct _ShelfWidgetsCompositedWindowClass ShelfWidgetsCompositedWindowClass;

#define SHELF_WIDGETS_TYPE_DOCK_WINDOW (shelf_widgets_dock_window_get_type ())
#define SHELF_WIDGETS_DOCK_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_WIDGETS_TYPE_DOCK_WINDOW, ShelfWidgetsDockWindow))
#define SHELF_WIDGETS_DOCK_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_WIDGETS_TYPE_DOCK_WINDOW, ShelfWidgetsDockWindowClass))
#define SHELF_WIDGETS_IS_DOCK_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_WIDGETS_TYPE_DOCK_WINDOW))
#define SHELF_WIDGETS_IS_DOCK_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_WIDGETS_TYPE_DOCK_WINDOW))
#define SHELF_WIDGETS_DOCK_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_WIDGETS_TYPE_DOCK_WINDOW, ShelfWidgetsDockWindowClass))

typedef struct _ShelfWidgetsDockWindow ShelfWidgetsDockWindow;
typedef struct _ShelfWidgetsDockWindowClass ShelfWidgetsDockWindowClass;

#define SHELF_DRAWING_TYPE_DOCK_RENDERER (shelf_drawing_dock_renderer_get_type ())
#define SHELF_DRAWING_DOCK_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_DRAWING_TYPE_DOCK_RENDERER, ShelfDrawingDockRenderer))
#define SHELF_DRAWING_DOCK_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_DRAWING_TYPE_DOCK_RENDERER, ShelfDrawingDockRendererClass))
#define SHELF_DRAWING_IS_DOCK_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_DRAWING_TYPE_DOCK_RENDERER))
#define SHELF_DRAWING_IS_DOCK_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_DRAWING_TYPE_DOCK_RENDERER))
#define SHELF_DRAWING_DOCK_RENDERER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_DRAWING_TYPE_DOCK_RENDERER, ShelfDrawingDockRendererClass))

typedef struct _ShelfDrawingDockRenderer ShelfDrawingDockRenderer;
typedef struct _ShelfDrawingDockRendererClass ShelfDrawingDockRendererClass;

#define SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER (shelf_system_dock_position_manager_get_type ())
#define SHELF_SYSTEM_DOCK_POSITION_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER, ShelfSystemDockPositionManager))
#define SHELF_SYSTEM_DOCK_POSITION_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER, ShelfSystemDockPositionManagerClass))
#define SHELF_SYSTEM_IS_DOCK_POSITION_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER))
#define SHELF_SYSTEM_IS_DOCK_POSITION_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER))
#define SHELF_SYSTEM_DOCK_POSITION_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER, ShelfSystemDockPositionManagerClass))

typedef struct _ShelfSystemDockPositionManager ShelfSystemDockPositionManager;
typedef struct _ShelfSystemDockPositionManagerClass ShelfSystemDockPositionManagerClass;

#define SHELF_ITEMS_TYPE_TAB_MANAGER (shelf_items_tab_manager_get_type ())
#define SHELF_ITEMS_TAB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManager))
#define SHELF_ITEMS_TAB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManagerClass))
#define SHELF_ITEMS_IS_TAB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_ITEMS_TYPE_TAB_MANAGER))
#define SHELF_ITEMS_IS_TAB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_ITEMS_TYPE_TAB_MANAGER))
#define SHELF_ITEMS_TAB_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManagerClass))

typedef struct _ShelfItemsTabManager ShelfItemsTabManager;
typedef struct _ShelfItemsTabManagerClass ShelfItemsTabManagerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _ShelfDockController {
	GObject parent_instance;
	ShelfDockControllerPrivate * priv;
	ShelfWidgetsDockWindow* window;
	ShelfDrawingDockRenderer* renderer;
	ShelfSystemDockPositionManager* position_manager;
	ShelfItemsTabManager* tab_manager;
};

struct _ShelfDockControllerClass {
	GObjectClass parent_class;
};


static gpointer shelf_dock_controller_parent_class = NULL;

GType shelf_dock_controller_get_type (void) G_GNUC_CONST;
GType shelf_widgets_composited_window_get_type (void) G_GNUC_CONST;
GType shelf_widgets_dock_window_get_type (void) G_GNUC_CONST;
GType shelf_drawing_dock_renderer_get_type (void) G_GNUC_CONST;
GType shelf_system_dock_position_manager_get_type (void) G_GNUC_CONST;
GType shelf_items_tab_manager_get_type (void) G_GNUC_CONST;
enum  {
	SHELF_DOCK_CONTROLLER_DUMMY_PROPERTY
};
ShelfDockController* shelf_dock_controller_new (void);
ShelfDockController* shelf_dock_controller_construct (GType object_type);
ShelfSystemDockPositionManager* shelf_system_dock_position_manager_new (ShelfDockController* controller);
ShelfSystemDockPositionManager* shelf_system_dock_position_manager_construct (GType object_type, ShelfDockController* controller);
ShelfWidgetsDockWindow* shelf_widgets_dock_window_new (ShelfDockController* controller);
ShelfWidgetsDockWindow* shelf_widgets_dock_window_construct (GType object_type, ShelfDockController* controller);
ShelfDrawingDockRenderer* shelf_drawing_dock_renderer_new (ShelfDockController* controller);
ShelfDrawingDockRenderer* shelf_drawing_dock_renderer_construct (GType object_type, ShelfDockController* controller);
ShelfItemsTabManager* shelf_items_tab_manager_new (ShelfDockController* controller);
ShelfItemsTabManager* shelf_items_tab_manager_construct (GType object_type, ShelfDockController* controller);
static void shelf_dock_controller_finalize (GObject* obj);


ShelfDockController* shelf_dock_controller_construct (GType object_type) {
	ShelfDockController * self = NULL;
	ShelfSystemDockPositionManager* _tmp0_;
	ShelfWidgetsDockWindow* _tmp1_;
	ShelfDrawingDockRenderer* _tmp2_;
	ShelfItemsTabManager* _tmp3_;
	ShelfWidgetsDockWindow* _tmp4_;
#line 38 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	self = (ShelfDockController*) g_object_new (object_type, NULL);
#line 41 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	_tmp0_ = shelf_system_dock_position_manager_new (self);
#line 41 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	_g_object_unref0 (self->position_manager);
#line 41 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	self->position_manager = _tmp0_;
#line 42 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	_tmp1_ = shelf_widgets_dock_window_new (self);
#line 42 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	g_object_ref_sink (_tmp1_);
#line 42 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	_g_object_unref0 (self->window);
#line 42 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	self->window = _tmp1_;
#line 43 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	_tmp2_ = shelf_drawing_dock_renderer_new (self);
#line 43 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	_g_object_unref0 (self->renderer);
#line 43 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	self->renderer = _tmp2_;
#line 44 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	_tmp3_ = shelf_items_tab_manager_new (self);
#line 44 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	_g_object_unref0 (self->tab_manager);
#line 44 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	self->tab_manager = _tmp3_;
#line 50 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	_tmp4_ = self->window;
#line 50 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp4_);
#line 38 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	return self;
#line 168 "DockController.c"
}


ShelfDockController* shelf_dock_controller_new (void) {
#line 38 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	return shelf_dock_controller_construct (SHELF_TYPE_DOCK_CONTROLLER);
#line 175 "DockController.c"
}


static void shelf_dock_controller_class_init (ShelfDockControllerClass * klass) {
#line 29 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	shelf_dock_controller_parent_class = g_type_class_peek_parent (klass);
#line 29 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	G_OBJECT_CLASS (klass)->finalize = shelf_dock_controller_finalize;
#line 184 "DockController.c"
}


static void shelf_dock_controller_instance_init (ShelfDockController * self) {
}


static void shelf_dock_controller_finalize (GObject* obj) {
	ShelfDockController * self;
#line 29 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHELF_TYPE_DOCK_CONTROLLER, ShelfDockController);
#line 33 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	_g_object_unref0 (self->window);
#line 34 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	_g_object_unref0 (self->renderer);
#line 35 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	_g_object_unref0 (self->position_manager);
#line 36 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	_g_object_unref0 (self->tab_manager);
#line 29 "/home/gwen/Programmation/vala/testgit/vala-sandbox/lib/DockController.vala"
	G_OBJECT_CLASS (shelf_dock_controller_parent_class)->finalize (obj);
#line 206 "DockController.c"
}


/**
 * A controller class for managing a single dock.
 */
GType shelf_dock_controller_get_type (void) {
	static volatile gsize shelf_dock_controller_type_id__volatile = 0;
	if (g_once_init_enter (&shelf_dock_controller_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ShelfDockControllerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) shelf_dock_controller_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ShelfDockController), 0, (GInstanceInitFunc) shelf_dock_controller_instance_init, NULL };
		GType shelf_dock_controller_type_id;
		shelf_dock_controller_type_id = g_type_register_static (G_TYPE_OBJECT, "ShelfDockController", &g_define_type_info, 0);
		g_once_init_leave (&shelf_dock_controller_type_id__volatile, shelf_dock_controller_type_id);
	}
	return shelf_dock_controller_type_id__volatile;
}



