/* DockWindow.c generated by valac 0.20.1.4-f5a54, the Vala compiler
 * generated from DockWindow.vala, do not modify */

/**/
/*  Copyright (C) 2011-2012 Robert Dyer, Michal Hruby, Rico Tzschichholz*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <cairo.h>
#include <stdio.h>


#define SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW (shelf_widgets_composited_window_get_type ())
#define SHELF_WIDGETS_COMPOSITED_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW, ShelfWidgetsCompositedWindow))
#define SHELF_WIDGETS_COMPOSITED_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW, ShelfWidgetsCompositedWindowClass))
#define SHELF_WIDGETS_IS_COMPOSITED_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW))
#define SHELF_WIDGETS_IS_COMPOSITED_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW))
#define SHELF_WIDGETS_COMPOSITED_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW, ShelfWidgetsCompositedWindowClass))

typedef struct _ShelfWidgetsCompositedWindow ShelfWidgetsCompositedWindow;
typedef struct _ShelfWidgetsCompositedWindowClass ShelfWidgetsCompositedWindowClass;
typedef struct _ShelfWidgetsCompositedWindowPrivate ShelfWidgetsCompositedWindowPrivate;

#define SHELF_WIDGETS_TYPE_DOCK_WINDOW (shelf_widgets_dock_window_get_type ())
#define SHELF_WIDGETS_DOCK_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_WIDGETS_TYPE_DOCK_WINDOW, ShelfWidgetsDockWindow))
#define SHELF_WIDGETS_DOCK_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_WIDGETS_TYPE_DOCK_WINDOW, ShelfWidgetsDockWindowClass))
#define SHELF_WIDGETS_IS_DOCK_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_WIDGETS_TYPE_DOCK_WINDOW))
#define SHELF_WIDGETS_IS_DOCK_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_WIDGETS_TYPE_DOCK_WINDOW))
#define SHELF_WIDGETS_DOCK_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_WIDGETS_TYPE_DOCK_WINDOW, ShelfWidgetsDockWindowClass))

typedef struct _ShelfWidgetsDockWindow ShelfWidgetsDockWindow;
typedef struct _ShelfWidgetsDockWindowClass ShelfWidgetsDockWindowClass;
typedef struct _ShelfWidgetsDockWindowPrivate ShelfWidgetsDockWindowPrivate;

#define SHELF_TYPE_DOCK_CONTROLLER (shelf_dock_controller_get_type ())
#define SHELF_DOCK_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_TYPE_DOCK_CONTROLLER, ShelfDockController))
#define SHELF_DOCK_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_TYPE_DOCK_CONTROLLER, ShelfDockControllerClass))
#define SHELF_IS_DOCK_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_TYPE_DOCK_CONTROLLER))
#define SHELF_IS_DOCK_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_TYPE_DOCK_CONTROLLER))
#define SHELF_DOCK_CONTROLLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_TYPE_DOCK_CONTROLLER, ShelfDockControllerClass))

typedef struct _ShelfDockController ShelfDockController;
typedef struct _ShelfDockControllerClass ShelfDockControllerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _ShelfDockControllerPrivate ShelfDockControllerPrivate;

#define SHELF_DRAWING_TYPE_DOCK_RENDERER (shelf_drawing_dock_renderer_get_type ())
#define SHELF_DRAWING_DOCK_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_DRAWING_TYPE_DOCK_RENDERER, ShelfDrawingDockRenderer))
#define SHELF_DRAWING_DOCK_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_DRAWING_TYPE_DOCK_RENDERER, ShelfDrawingDockRendererClass))
#define SHELF_DRAWING_IS_DOCK_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_DRAWING_TYPE_DOCK_RENDERER))
#define SHELF_DRAWING_IS_DOCK_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_DRAWING_TYPE_DOCK_RENDERER))
#define SHELF_DRAWING_DOCK_RENDERER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_DRAWING_TYPE_DOCK_RENDERER, ShelfDrawingDockRendererClass))

typedef struct _ShelfDrawingDockRenderer ShelfDrawingDockRenderer;
typedef struct _ShelfDrawingDockRendererClass ShelfDrawingDockRendererClass;

#define SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER (shelf_system_dock_position_manager_get_type ())
#define SHELF_SYSTEM_DOCK_POSITION_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER, ShelfSystemDockPositionManager))
#define SHELF_SYSTEM_DOCK_POSITION_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER, ShelfSystemDockPositionManagerClass))
#define SHELF_SYSTEM_IS_DOCK_POSITION_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER))
#define SHELF_SYSTEM_IS_DOCK_POSITION_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER))
#define SHELF_SYSTEM_DOCK_POSITION_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_SYSTEM_TYPE_DOCK_POSITION_MANAGER, ShelfSystemDockPositionManagerClass))

typedef struct _ShelfSystemDockPositionManager ShelfSystemDockPositionManager;
typedef struct _ShelfSystemDockPositionManagerClass ShelfSystemDockPositionManagerClass;

#define SHELF_ITEMS_TYPE_TAB_MANAGER (shelf_items_tab_manager_get_type ())
#define SHELF_ITEMS_TAB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManager))
#define SHELF_ITEMS_TAB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManagerClass))
#define SHELF_ITEMS_IS_TAB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELF_ITEMS_TYPE_TAB_MANAGER))
#define SHELF_ITEMS_IS_TAB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELF_ITEMS_TYPE_TAB_MANAGER))
#define SHELF_ITEMS_TAB_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHELF_ITEMS_TYPE_TAB_MANAGER, ShelfItemsTabManagerClass))

typedef struct _ShelfItemsTabManager ShelfItemsTabManager;
typedef struct _ShelfItemsTabManagerClass ShelfItemsTabManagerClass;

struct _ShelfWidgetsCompositedWindow {
	GtkWindow parent_instance;
	ShelfWidgetsCompositedWindowPrivate * priv;
};

struct _ShelfWidgetsCompositedWindowClass {
	GtkWindowClass parent_class;
};

struct _ShelfWidgetsDockWindow {
	ShelfWidgetsCompositedWindow parent_instance;
	ShelfWidgetsDockWindowPrivate * priv;
};

struct _ShelfWidgetsDockWindowClass {
	ShelfWidgetsCompositedWindowClass parent_class;
};

struct _ShelfWidgetsDockWindowPrivate {
	gboolean firstDraw;
	ShelfDockController* _controller;
};

struct _ShelfDockController {
	GObject parent_instance;
	ShelfDockControllerPrivate * priv;
	ShelfWidgetsDockWindow* window;
	ShelfDrawingDockRenderer* renderer;
	ShelfSystemDockPositionManager* position_manager;
	ShelfItemsTabManager* tab_manager;
};

struct _ShelfDockControllerClass {
	GObjectClass parent_class;
};


static gpointer shelf_widgets_dock_window_parent_class = NULL;

GType shelf_widgets_composited_window_get_type (void) G_GNUC_CONST;
GType shelf_widgets_dock_window_get_type (void) G_GNUC_CONST;
GType shelf_dock_controller_get_type (void) G_GNUC_CONST;
#define SHELF_WIDGETS_DOCK_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SHELF_WIDGETS_TYPE_DOCK_WINDOW, ShelfWidgetsDockWindowPrivate))
enum  {
	SHELF_WIDGETS_DOCK_WINDOW_DUMMY_PROPERTY,
	SHELF_WIDGETS_DOCK_WINDOW_CONTROLLER
};
ShelfWidgetsDockWindow* shelf_widgets_dock_window_new (ShelfDockController* controller);
ShelfWidgetsDockWindow* shelf_widgets_dock_window_construct (GType object_type, ShelfDockController* controller);
static gboolean shelf_widgets_dock_window_real_button_press_event (GtkWidget* base, GdkEventButton* event);
static gboolean shelf_widgets_dock_window_real_button_release_event (GtkWidget* base, GdkEventButton* event);
static gboolean shelf_widgets_dock_window_real_enter_notify_event (GtkWidget* base, GdkEventCrossing* event);
static gboolean shelf_widgets_dock_window_real_leave_notify_event (GtkWidget* base, GdkEventCrossing* event);
static gboolean shelf_widgets_dock_window_real_motion_notify_event (GtkWidget* base, GdkEventMotion* event);
static ShelfDockController* shelf_widgets_dock_window_get_controller (ShelfWidgetsDockWindow* self);
GType shelf_drawing_dock_renderer_get_type (void) G_GNUC_CONST;
GType shelf_system_dock_position_manager_get_type (void) G_GNUC_CONST;
GType shelf_items_tab_manager_get_type (void) G_GNUC_CONST;
void shelf_items_tab_manager_check_tab_mouse_collision (ShelfItemsTabManager* self, GdkEventMotion* event);
static gboolean shelf_widgets_dock_window_real_scroll_event (GtkWidget* base, GdkEventScroll* event);
static gboolean shelf_widgets_dock_window_real_draw (GtkWidget* base, cairo_t* cr);
void shelf_system_dock_position_manager_initialize (ShelfSystemDockPositionManager* self);
gboolean shelf_drawing_dock_renderer_draw (ShelfDrawingDockRenderer* self, cairo_t* cr);
static void shelf_widgets_dock_window_set_controller (ShelfWidgetsDockWindow* self, ShelfDockController* value);
static GObject * shelf_widgets_dock_window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void shelf_widgets_dock_window_finalize (GObject* obj);
static void _vala_shelf_widgets_dock_window_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_shelf_widgets_dock_window_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


/**
 * Creates a new dock window.
 */
ShelfWidgetsDockWindow* shelf_widgets_dock_window_construct (GType object_type, ShelfDockController* controller) {
	ShelfWidgetsDockWindow * self = NULL;
	ShelfDockController* _tmp0_;
#line 45 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	g_return_val_if_fail (controller != NULL, NULL);
#line 47 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	_tmp0_ = controller;
#line 47 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	self = (ShelfWidgetsDockWindow*) g_object_new (object_type, "controller", _tmp0_, "type", GTK_WINDOW_TOPLEVEL, "type-hint", GDK_WINDOW_TYPE_HINT_DOCK, NULL);
#line 45 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	return self;
#line 178 "DockWindow.c"
}


ShelfWidgetsDockWindow* shelf_widgets_dock_window_new (ShelfDockController* controller) {
#line 45 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	return shelf_widgets_dock_window_construct (SHELF_WIDGETS_TYPE_DOCK_WINDOW, controller);
#line 185 "DockWindow.c"
}


/**
 * {@inheritDoc}
 */
static gboolean shelf_widgets_dock_window_real_button_press_event (GtkWidget* base, GdkEventButton* event) {
	ShelfWidgetsDockWindow * self;
	gboolean result = FALSE;
#line 74 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	self = (ShelfWidgetsDockWindow*) base;
#line 74 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 76 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	result = TRUE;
#line 76 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	return result;
#line 203 "DockWindow.c"
}


/**
 * {@inheritDoc}
 */
static gboolean shelf_widgets_dock_window_real_button_release_event (GtkWidget* base, GdkEventButton* event) {
	ShelfWidgetsDockWindow * self;
	gboolean result = FALSE;
#line 82 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	self = (ShelfWidgetsDockWindow*) base;
#line 82 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 85 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	result = TRUE;
#line 85 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	return result;
#line 221 "DockWindow.c"
}


/**
 * {@inheritDoc}
 */
static gboolean shelf_widgets_dock_window_real_enter_notify_event (GtkWidget* base, GdkEventCrossing* event) {
	ShelfWidgetsDockWindow * self;
	gboolean result = FALSE;
#line 91 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	self = (ShelfWidgetsDockWindow*) base;
#line 91 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	result = TRUE;
#line 94 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	return result;
#line 239 "DockWindow.c"
}


/**
 * {@inheritDoc}
 */
static gboolean shelf_widgets_dock_window_real_leave_notify_event (GtkWidget* base, GdkEventCrossing* event) {
	ShelfWidgetsDockWindow * self;
	gboolean result = FALSE;
#line 100 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	self = (ShelfWidgetsDockWindow*) base;
#line 100 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 103 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	result = TRUE;
#line 103 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	return result;
#line 257 "DockWindow.c"
}


/**
 * {@inheritDoc}
 */
static gboolean shelf_widgets_dock_window_real_motion_notify_event (GtkWidget* base, GdkEventMotion* event) {
	ShelfWidgetsDockWindow * self;
	gboolean result = FALSE;
	ShelfDockController* _tmp0_;
	ShelfItemsTabManager* _tmp1_;
	GdkEventMotion _tmp2_;
#line 109 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	self = (ShelfWidgetsDockWindow*) base;
#line 109 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 111 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	_tmp0_ = self->priv->_controller;
#line 111 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	_tmp1_ = _tmp0_->tab_manager;
#line 111 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	_tmp2_ = *event;
#line 111 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	shelf_items_tab_manager_check_tab_mouse_collision (_tmp1_, &_tmp2_);
#line 112 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	gtk_widget_queue_draw ((GtkWidget*) self);
#line 113 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	result = TRUE;
#line 113 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	return result;
#line 288 "DockWindow.c"
}


/**
 * {@inheritDoc}
 */
static gboolean shelf_widgets_dock_window_real_scroll_event (GtkWidget* base, GdkEventScroll* event) {
	ShelfWidgetsDockWindow * self;
	gboolean result = FALSE;
#line 119 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	self = (ShelfWidgetsDockWindow*) base;
#line 119 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 122 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	result = TRUE;
#line 122 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	return result;
#line 306 "DockWindow.c"
}


/**
 * {@inheritDoc}
 */
static gboolean shelf_widgets_dock_window_real_draw (GtkWidget* base, cairo_t* cr) {
	ShelfWidgetsDockWindow * self;
	gboolean result = FALSE;
	gboolean _tmp0_;
	FILE* _tmp3_;
	ShelfDockController* _tmp4_;
	ShelfDrawingDockRenderer* _tmp5_;
	cairo_t* _tmp6_;
#line 128 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	self = (ShelfWidgetsDockWindow*) base;
#line 128 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	g_return_val_if_fail (cr != NULL, FALSE);
#line 130 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	_tmp0_ = self->priv->firstDraw;
#line 130 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	if (_tmp0_) {
#line 329 "DockWindow.c"
		ShelfDockController* _tmp1_;
		ShelfSystemDockPositionManager* _tmp2_;
#line 132 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
		self->priv->firstDraw = FALSE;
#line 133 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
		_tmp1_ = self->priv->_controller;
#line 133 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
		_tmp2_ = _tmp1_->position_manager;
#line 133 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
		shelf_system_dock_position_manager_initialize (_tmp2_);
#line 340 "DockWindow.c"
	}
#line 135 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	_tmp3_ = stdout;
#line 135 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	fprintf (_tmp3_, "draw DockWindow\n");
#line 137 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	_tmp4_ = self->priv->_controller;
#line 137 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	_tmp5_ = _tmp4_->renderer;
#line 137 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	_tmp6_ = cr;
#line 137 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	shelf_drawing_dock_renderer_draw (_tmp5_, _tmp6_);
#line 138 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	result = TRUE;
#line 138 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	return result;
#line 358 "DockWindow.c"
}


static ShelfDockController* shelf_widgets_dock_window_get_controller (ShelfWidgetsDockWindow* self) {
	ShelfDockController* result;
	ShelfDockController* _tmp0_;
#line 40 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 40 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	_tmp0_ = self->priv->_controller;
#line 40 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	result = _tmp0_;
#line 40 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	return result;
#line 373 "DockWindow.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 40 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	return self ? g_object_ref (self) : NULL;
#line 380 "DockWindow.c"
}


static void shelf_widgets_dock_window_set_controller (ShelfWidgetsDockWindow* self, ShelfDockController* value) {
	ShelfDockController* _tmp0_;
	ShelfDockController* _tmp1_;
#line 40 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	g_return_if_fail (self != NULL);
#line 40 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	_tmp0_ = value;
#line 40 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 40 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	_g_object_unref0 (self->priv->_controller);
#line 40 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	self->priv->_controller = _tmp1_;
#line 40 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	g_object_notify ((GObject *) self, "controller");
#line 399 "DockWindow.c"
}


static GObject * shelf_widgets_dock_window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	ShelfWidgetsDockWindow * self;
#line 50 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	parent_class = G_OBJECT_CLASS (shelf_widgets_dock_window_parent_class);
#line 50 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 50 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHELF_WIDGETS_TYPE_DOCK_WINDOW, ShelfWidgetsDockWindow);
#line 52 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	gtk_window_set_accept_focus ((GtkWindow*) self, FALSE);
#line 53 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	g_object_set ((GtkWidget*) self, "can-focus", FALSE, NULL);
#line 54 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	gtk_window_set_skip_pager_hint ((GtkWindow*) self, TRUE);
#line 55 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	gtk_window_set_skip_taskbar_hint ((GtkWindow*) self, TRUE);
#line 57 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	gtk_window_stick ((GtkWindow*) self);
#line 59 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	gtk_widget_add_events ((GtkWidget*) self, (gint) (((((GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK) | GDK_ENTER_NOTIFY_MASK) | GDK_LEAVE_NOTIFY_MASK) | GDK_POINTER_MOTION_MASK) | GDK_SCROLL_MASK));
#line 50 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	return obj;
#line 427 "DockWindow.c"
}


static void shelf_widgets_dock_window_class_init (ShelfWidgetsDockWindowClass * klass) {
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	shelf_widgets_dock_window_parent_class = g_type_class_peek_parent (klass);
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	g_type_class_add_private (klass, sizeof (ShelfWidgetsDockWindowPrivate));
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	GTK_WIDGET_CLASS (klass)->button_press_event = shelf_widgets_dock_window_real_button_press_event;
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	GTK_WIDGET_CLASS (klass)->button_release_event = shelf_widgets_dock_window_real_button_release_event;
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	GTK_WIDGET_CLASS (klass)->enter_notify_event = shelf_widgets_dock_window_real_enter_notify_event;
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	GTK_WIDGET_CLASS (klass)->leave_notify_event = shelf_widgets_dock_window_real_leave_notify_event;
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	GTK_WIDGET_CLASS (klass)->motion_notify_event = shelf_widgets_dock_window_real_motion_notify_event;
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	GTK_WIDGET_CLASS (klass)->scroll_event = shelf_widgets_dock_window_real_scroll_event;
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	GTK_WIDGET_CLASS (klass)->draw = shelf_widgets_dock_window_real_draw;
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_shelf_widgets_dock_window_get_property;
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_shelf_widgets_dock_window_set_property;
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	G_OBJECT_CLASS (klass)->constructor = shelf_widgets_dock_window_constructor;
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	G_OBJECT_CLASS (klass)->finalize = shelf_widgets_dock_window_finalize;
#line 458 "DockWindow.c"
	/**
	 * The controller for this dock.
	 */
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SHELF_WIDGETS_DOCK_WINDOW_CONTROLLER, g_param_spec_object ("controller", "controller", "controller", SHELF_TYPE_DOCK_CONTROLLER, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 464 "DockWindow.c"
}


static void shelf_widgets_dock_window_instance_init (ShelfWidgetsDockWindow * self) {
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	self->priv = SHELF_WIDGETS_DOCK_WINDOW_GET_PRIVATE (self);
#line 35 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	self->priv->firstDraw = TRUE;
#line 473 "DockWindow.c"
}


static void shelf_widgets_dock_window_finalize (GObject* obj) {
	ShelfWidgetsDockWindow * self;
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHELF_WIDGETS_TYPE_DOCK_WINDOW, ShelfWidgetsDockWindow);
#line 40 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	_g_object_unref0 (self->priv->_controller);
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	G_OBJECT_CLASS (shelf_widgets_dock_window_parent_class)->finalize (obj);
#line 485 "DockWindow.c"
}


/**
 * The main window for all docks.
 */
GType shelf_widgets_dock_window_get_type (void) {
	static volatile gsize shelf_widgets_dock_window_type_id__volatile = 0;
	if (g_once_init_enter (&shelf_widgets_dock_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ShelfWidgetsDockWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) shelf_widgets_dock_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ShelfWidgetsDockWindow), 0, (GInstanceInitFunc) shelf_widgets_dock_window_instance_init, NULL };
		GType shelf_widgets_dock_window_type_id;
		shelf_widgets_dock_window_type_id = g_type_register_static (SHELF_WIDGETS_TYPE_COMPOSITED_WINDOW, "ShelfWidgetsDockWindow", &g_define_type_info, 0);
		g_once_init_leave (&shelf_widgets_dock_window_type_id__volatile, shelf_widgets_dock_window_type_id);
	}
	return shelf_widgets_dock_window_type_id__volatile;
}


static void _vala_shelf_widgets_dock_window_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	ShelfWidgetsDockWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SHELF_WIDGETS_TYPE_DOCK_WINDOW, ShelfWidgetsDockWindow);
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	switch (property_id) {
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
		case SHELF_WIDGETS_DOCK_WINDOW_CONTROLLER:
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
		g_value_set_object (value, shelf_widgets_dock_window_get_controller (self));
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
		break;
#line 515 "DockWindow.c"
		default:
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
		break;
#line 521 "DockWindow.c"
	}
}


static void _vala_shelf_widgets_dock_window_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	ShelfWidgetsDockWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SHELF_WIDGETS_TYPE_DOCK_WINDOW, ShelfWidgetsDockWindow);
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
	switch (property_id) {
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
		case SHELF_WIDGETS_DOCK_WINDOW_CONTROLLER:
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
		shelf_widgets_dock_window_set_controller (self, g_value_get_object (value));
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
		break;
#line 537 "DockWindow.c"
		default:
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 32 "/home/gwen/Programmation/vala/vala-sandbox/lib/Widgets/DockWindow.vala"
		break;
#line 543 "DockWindow.c"
	}
}



