/* PlankMain.c generated by valac 0.20.1.4-f5a54, the Vala compiler
 * generated from PlankMain.vala, do not modify */

/**/
/*  Copyright (C) 2011-2012 Robert Dyer, Rico Tzschichholz*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include "shelf.h"
#include <stdlib.h>
#include <string.h>


#define PLANK_MAIN_TYPE_PLANK_MAIN (plank_main_plank_main_get_type ())
#define PLANK_MAIN_PLANK_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLANK_MAIN_TYPE_PLANK_MAIN, PlankMainPlankMain))
#define PLANK_MAIN_PLANK_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLANK_MAIN_TYPE_PLANK_MAIN, PlankMainPlankMainClass))
#define PLANK_MAIN_IS_PLANK_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLANK_MAIN_TYPE_PLANK_MAIN))
#define PLANK_MAIN_IS_PLANK_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLANK_MAIN_TYPE_PLANK_MAIN))
#define PLANK_MAIN_PLANK_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLANK_MAIN_TYPE_PLANK_MAIN, PlankMainPlankMainClass))

typedef struct _PlankMainPlankMain PlankMainPlankMain;
typedef struct _PlankMainPlankMainClass PlankMainPlankMainClass;
typedef struct _PlankMainPlankMainPrivate PlankMainPlankMainPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _PlankMainPlankMain {
	ShelfFactoriesAbstractMain parent_instance;
	PlankMainPlankMainPrivate * priv;
};

struct _PlankMainPlankMainClass {
	ShelfFactoriesAbstractMainClass parent_class;
};


static gpointer plank_main_plank_main_parent_class = NULL;

GType plank_main_plank_main_get_type (void) G_GNUC_CONST;
enum  {
	PLANK_MAIN_PLANK_MAIN_DUMMY_PROPERTY
};
gint plank_main_plank_main_main (gchar** args, int args_length1);
PlankMainPlankMain* plank_main_plank_main_new (void);
PlankMainPlankMain* plank_main_plank_main_construct (GType object_type);


gint plank_main_plank_main_main (gchar** args, int args_length1) {
	gint result = 0;
	PlankMainPlankMain* _tmp0_;
	PlankMainPlankMain* main_class;
	ShelfFactoriesItemFactory* _tmp1_;
	ShelfFactoriesItemFactory* _tmp2_;
	gint _tmp3_ = 0;
#line 26 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	_tmp0_ = plank_main_plank_main_new ();
#line 26 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	main_class = _tmp0_;
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	_tmp1_ = shelf_factories_item_factory_new ();
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	_tmp2_ = _tmp1_;
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	shelf_factories_factory_init ((ShelfFactoriesAbstractMain*) main_class, _tmp2_);
#line 27 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	_g_object_unref0 (_tmp2_);
#line 28 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	_tmp3_ = shelf_factories_abstract_main_run ((ShelfFactoriesAbstractMain*) main_class, &args, &args_length1);
#line 28 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	result = _tmp3_;
#line 28 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	_g_object_unref0 (main_class);
#line 28 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	return result;
#line 90 "PlankMain.c"
}


int main (int argc, char ** argv) {
#line 24 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	g_type_init ();
#line 24 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	return plank_main_plank_main_main (argv, argc);
#line 99 "PlankMain.c"
}


PlankMainPlankMain* plank_main_plank_main_construct (GType object_type) {
	PlankMainPlankMain * self = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
#line 31 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	self = (PlankMainPlankMain*) shelf_factories_abstract_main_construct (object_type);
#line 33 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	_tmp0_ = g_strdup ("Shelf");
#line 33 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	_g_free0 (((ShelfFactoriesAbstractMain*) self)->program_name);
#line 33 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	((ShelfFactoriesAbstractMain*) self)->program_name = _tmp0_;
#line 34 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	_tmp1_ = g_strdup ("shelf");
#line 34 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	_g_free0 (((ShelfFactoriesAbstractMain*) self)->exec_name);
#line 34 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	((ShelfFactoriesAbstractMain*) self)->exec_name = _tmp1_;
#line 31 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	return self;
#line 123 "PlankMain.c"
}


PlankMainPlankMain* plank_main_plank_main_new (void) {
#line 31 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	return plank_main_plank_main_construct (PLANK_MAIN_TYPE_PLANK_MAIN);
#line 130 "PlankMain.c"
}


static void plank_main_plank_main_class_init (PlankMainPlankMainClass * klass) {
#line 22 "/home/gwen/Programmation/vala/vala-sandbox/src/PlankMain.vala"
	plank_main_plank_main_parent_class = g_type_class_peek_parent (klass);
#line 137 "PlankMain.c"
}


static void plank_main_plank_main_instance_init (PlankMainPlankMain * self) {
}


GType plank_main_plank_main_get_type (void) {
	static volatile gsize plank_main_plank_main_type_id__volatile = 0;
	if (g_once_init_enter (&plank_main_plank_main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PlankMainPlankMainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) plank_main_plank_main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PlankMainPlankMain), 0, (GInstanceInitFunc) plank_main_plank_main_instance_init, NULL };
		GType plank_main_plank_main_type_id;
		plank_main_plank_main_type_id = g_type_register_static (SHELF_FACTORIES_TYPE_ABSTRACT_MAIN, "PlankMainPlankMain", &g_define_type_info, 0);
		g_once_init_leave (&plank_main_plank_main_type_id__volatile, plank_main_plank_main_type_id);
	}
	return plank_main_plank_main_type_id__volatile;
}



